// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UploadLaLoRequestBean.proto

package com.halo.ap.web.cmd.uploadlalo.protobuf;

public final class UploadLaLoRequestBeanOuterClass {
  private UploadLaLoRequestBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UploadLaLoRequestBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    java.util.List<UploadLaLoRequestBean.LaloData>
        getLaloDataList();
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    UploadLaLoRequestBean.LaloData getLaloData(int index);
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    int getLaloDataCount();
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean}
   */
  public  static final class UploadLaLoRequestBean extends
      com.google.protobuf.GeneratedMessageLite<
          UploadLaLoRequestBean, UploadLaLoRequestBean.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean)
      UploadLaLoRequestBeanOrBuilder {
    private UploadLaLoRequestBean() {
      laloData_ = emptyProtobufList();
    }
    public interface LaloDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional string bssid = 1;</code>
       */
      String getBssid();
      /**
       * <code>optional string bssid = 1;</code>
       */
      com.google.protobuf.ByteString
          getBssidBytes();

      /**
       * <code>optional string secLevel = 2;</code>
       */
      String getSecLevel();
      /**
       * <code>optional string secLevel = 2;</code>
       */
      com.google.protobuf.ByteString
          getSecLevelBytes();

      /**
       * <code>optional string la = 3;</code>
       */
      String getLa();
      /**
       * <code>optional string la = 3;</code>
       */
      com.google.protobuf.ByteString
          getLaBytes();

      /**
       * <code>optional string lo = 4;</code>
       */
      String getLo();
      /**
       * <code>optional string lo = 4;</code>
       */
      com.google.protobuf.ByteString
          getLoBytes();

      /**
       * <code>optional string mapSP = 5;</code>
       */
      String getMapSP();
      /**
       * <code>optional string mapSP = 5;</code>
       */
      com.google.protobuf.ByteString
          getMapSPBytes();

      /**
       * <code>optional string rssi = 6;</code>
       */
      String getRssi();
      /**
       * <code>optional string rssi = 6;</code>
       */
      com.google.protobuf.ByteString
          getRssiBytes();

      /**
       * <code>optional string ls = 7;</code>
       */
      String getLs();
      /**
       * <code>optional string ls = 7;</code>
       */
      com.google.protobuf.ByteString
          getLsBytes();

      /**
       * <code>optional string ts = 8;</code>
       */
      String getTs();
      /**
       * <code>optional string ts = 8;</code>
       */
      com.google.protobuf.ByteString
          getTsBytes();

      /**
       * <code>optional string sn = 9;</code>
       */
      String getSn();
      /**
       * <code>optional string sn = 9;</code>
       */
      com.google.protobuf.ByteString
          getSnBytes();

      /**
       * <code>optional string lac = 10;</code>
       */
      String getLac();
      /**
       * <code>optional string lac = 10;</code>
       */
      com.google.protobuf.ByteString
          getLacBytes();

      /**
       * <code>optional string cid = 11;</code>
       */
      String getCid();
      /**
       * <code>optional string cid = 11;</code>
       */
      com.google.protobuf.ByteString
          getCidBytes();

      /**
       * <code>optional string ssid = 12;</code>
       */
      String getSsid();
      /**
       * <code>optional string ssid = 12;</code>
       */
      com.google.protobuf.ByteString
          getSsidBytes();
    }
    /**
     * Protobuf type {@code com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData}
     */
    public  static final class LaloData extends
        com.google.protobuf.GeneratedMessageLite<
            LaloData, LaloData.Builder> implements
        // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData)
        LaloDataOrBuilder {
      private LaloData() {
        bssid_ = "";
        secLevel_ = "";
        la_ = "";
        lo_ = "";
        mapSP_ = "";
        rssi_ = "";
        ls_ = "";
        ts_ = "";
        sn_ = "";
        lac_ = "";
        cid_ = "";
        ssid_ = "";
      }
      public static final int BSSID_FIELD_NUMBER = 1;
      private String bssid_;
      /**
       * <code>optional string bssid = 1;</code>
       */
      public String getBssid() {
        return bssid_;
      }
      /**
       * <code>optional string bssid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBssidBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(bssid_);
      }
      /**
       * <code>optional string bssid = 1;</code>
       */
      private void setBssid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bssid_ = value;
      }
      /**
       * <code>optional string bssid = 1;</code>
       */
      private void clearBssid() {
        
        bssid_ = getDefaultInstance().getBssid();
      }
      /**
       * <code>optional string bssid = 1;</code>
       */
      private void setBssidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bssid_ = value.toStringUtf8();
      }

      public static final int SECLEVEL_FIELD_NUMBER = 2;
      private String secLevel_;
      /**
       * <code>optional string secLevel = 2;</code>
       */
      public String getSecLevel() {
        return secLevel_;
      }
      /**
       * <code>optional string secLevel = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSecLevelBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(secLevel_);
      }
      /**
       * <code>optional string secLevel = 2;</code>
       */
      private void setSecLevel(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secLevel_ = value;
      }
      /**
       * <code>optional string secLevel = 2;</code>
       */
      private void clearSecLevel() {
        
        secLevel_ = getDefaultInstance().getSecLevel();
      }
      /**
       * <code>optional string secLevel = 2;</code>
       */
      private void setSecLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secLevel_ = value.toStringUtf8();
      }

      public static final int LA_FIELD_NUMBER = 3;
      private String la_;
      /**
       * <code>optional string la = 3;</code>
       */
      public String getLa() {
        return la_;
      }
      /**
       * <code>optional string la = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLaBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(la_);
      }
      /**
       * <code>optional string la = 3;</code>
       */
      private void setLa(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        la_ = value;
      }
      /**
       * <code>optional string la = 3;</code>
       */
      private void clearLa() {
        
        la_ = getDefaultInstance().getLa();
      }
      /**
       * <code>optional string la = 3;</code>
       */
      private void setLaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        la_ = value.toStringUtf8();
      }

      public static final int LO_FIELD_NUMBER = 4;
      private String lo_;
      /**
       * <code>optional string lo = 4;</code>
       */
      public String getLo() {
        return lo_;
      }
      /**
       * <code>optional string lo = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLoBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(lo_);
      }
      /**
       * <code>optional string lo = 4;</code>
       */
      private void setLo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lo_ = value;
      }
      /**
       * <code>optional string lo = 4;</code>
       */
      private void clearLo() {
        
        lo_ = getDefaultInstance().getLo();
      }
      /**
       * <code>optional string lo = 4;</code>
       */
      private void setLoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lo_ = value.toStringUtf8();
      }

      public static final int MAPSP_FIELD_NUMBER = 5;
      private String mapSP_;
      /**
       * <code>optional string mapSP = 5;</code>
       */
      public String getMapSP() {
        return mapSP_;
      }
      /**
       * <code>optional string mapSP = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMapSPBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(mapSP_);
      }
      /**
       * <code>optional string mapSP = 5;</code>
       */
      private void setMapSP(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mapSP_ = value;
      }
      /**
       * <code>optional string mapSP = 5;</code>
       */
      private void clearMapSP() {
        
        mapSP_ = getDefaultInstance().getMapSP();
      }
      /**
       * <code>optional string mapSP = 5;</code>
       */
      private void setMapSPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mapSP_ = value.toStringUtf8();
      }

      public static final int RSSI_FIELD_NUMBER = 6;
      private String rssi_;
      /**
       * <code>optional string rssi = 6;</code>
       */
      public String getRssi() {
        return rssi_;
      }
      /**
       * <code>optional string rssi = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRssiBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(rssi_);
      }
      /**
       * <code>optional string rssi = 6;</code>
       */
      private void setRssi(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rssi_ = value;
      }
      /**
       * <code>optional string rssi = 6;</code>
       */
      private void clearRssi() {
        
        rssi_ = getDefaultInstance().getRssi();
      }
      /**
       * <code>optional string rssi = 6;</code>
       */
      private void setRssiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rssi_ = value.toStringUtf8();
      }

      public static final int LS_FIELD_NUMBER = 7;
      private String ls_;
      /**
       * <code>optional string ls = 7;</code>
       */
      public String getLs() {
        return ls_;
      }
      /**
       * <code>optional string ls = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLsBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(ls_);
      }
      /**
       * <code>optional string ls = 7;</code>
       */
      private void setLs(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ls_ = value;
      }
      /**
       * <code>optional string ls = 7;</code>
       */
      private void clearLs() {
        
        ls_ = getDefaultInstance().getLs();
      }
      /**
       * <code>optional string ls = 7;</code>
       */
      private void setLsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ls_ = value.toStringUtf8();
      }

      public static final int TS_FIELD_NUMBER = 8;
      private String ts_;
      /**
       * <code>optional string ts = 8;</code>
       */
      public String getTs() {
        return ts_;
      }
      /**
       * <code>optional string ts = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTsBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(ts_);
      }
      /**
       * <code>optional string ts = 8;</code>
       */
      private void setTs(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ts_ = value;
      }
      /**
       * <code>optional string ts = 8;</code>
       */
      private void clearTs() {
        
        ts_ = getDefaultInstance().getTs();
      }
      /**
       * <code>optional string ts = 8;</code>
       */
      private void setTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ts_ = value.toStringUtf8();
      }

      public static final int SN_FIELD_NUMBER = 9;
      private String sn_;
      /**
       * <code>optional string sn = 9;</code>
       */
      public String getSn() {
        return sn_;
      }
      /**
       * <code>optional string sn = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(sn_);
      }
      /**
       * <code>optional string sn = 9;</code>
       */
      private void setSn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sn_ = value;
      }
      /**
       * <code>optional string sn = 9;</code>
       */
      private void clearSn() {
        
        sn_ = getDefaultInstance().getSn();
      }
      /**
       * <code>optional string sn = 9;</code>
       */
      private void setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sn_ = value.toStringUtf8();
      }

      public static final int LAC_FIELD_NUMBER = 10;
      private String lac_;
      /**
       * <code>optional string lac = 10;</code>
       */
      public String getLac() {
        return lac_;
      }
      /**
       * <code>optional string lac = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLacBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(lac_);
      }
      /**
       * <code>optional string lac = 10;</code>
       */
      private void setLac(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lac_ = value;
      }
      /**
       * <code>optional string lac = 10;</code>
       */
      private void clearLac() {
        
        lac_ = getDefaultInstance().getLac();
      }
      /**
       * <code>optional string lac = 10;</code>
       */
      private void setLacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lac_ = value.toStringUtf8();
      }

      public static final int CID_FIELD_NUMBER = 11;
      private String cid_;
      /**
       * <code>optional string cid = 11;</code>
       */
      public String getCid() {
        return cid_;
      }
      /**
       * <code>optional string cid = 11;</code>
       */
      public com.google.protobuf.ByteString
          getCidBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(cid_);
      }
      /**
       * <code>optional string cid = 11;</code>
       */
      private void setCid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cid_ = value;
      }
      /**
       * <code>optional string cid = 11;</code>
       */
      private void clearCid() {
        
        cid_ = getDefaultInstance().getCid();
      }
      /**
       * <code>optional string cid = 11;</code>
       */
      private void setCidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cid_ = value.toStringUtf8();
      }

      public static final int SSID_FIELD_NUMBER = 12;
      private String ssid_;
      /**
       * <code>optional string ssid = 12;</code>
       */
      public String getSsid() {
        return ssid_;
      }
      /**
       * <code>optional string ssid = 12;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(ssid_);
      }
      /**
       * <code>optional string ssid = 12;</code>
       */
      private void setSsid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ssid_ = value;
      }
      /**
       * <code>optional string ssid = 12;</code>
       */
      private void clearSsid() {
        
        ssid_ = getDefaultInstance().getSsid();
      }
      /**
       * <code>optional string ssid = 12;</code>
       */
      private void setSsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ssid_ = value.toStringUtf8();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!bssid_.isEmpty()) {
          output.writeString(1, getBssid());
        }
        if (!secLevel_.isEmpty()) {
          output.writeString(2, getSecLevel());
        }
        if (!la_.isEmpty()) {
          output.writeString(3, getLa());
        }
        if (!lo_.isEmpty()) {
          output.writeString(4, getLo());
        }
        if (!mapSP_.isEmpty()) {
          output.writeString(5, getMapSP());
        }
        if (!rssi_.isEmpty()) {
          output.writeString(6, getRssi());
        }
        if (!ls_.isEmpty()) {
          output.writeString(7, getLs());
        }
        if (!ts_.isEmpty()) {
          output.writeString(8, getTs());
        }
        if (!sn_.isEmpty()) {
          output.writeString(9, getSn());
        }
        if (!lac_.isEmpty()) {
          output.writeString(10, getLac());
        }
        if (!cid_.isEmpty()) {
          output.writeString(11, getCid());
        }
        if (!ssid_.isEmpty()) {
          output.writeString(12, getSsid());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!bssid_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getBssid());
        }
        if (!secLevel_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getSecLevel());
        }
        if (!la_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(3, getLa());
        }
        if (!lo_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(4, getLo());
        }
        if (!mapSP_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(5, getMapSP());
        }
        if (!rssi_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(6, getRssi());
        }
        if (!ls_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(7, getLs());
        }
        if (!ts_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(8, getTs());
        }
        if (!sn_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(9, getSn());
        }
        if (!lac_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(10, getLac());
        }
        if (!cid_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(11, getCid());
        }
        if (!ssid_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(12, getSsid());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static LaloData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static LaloData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static LaloData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static LaloData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static LaloData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static LaloData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static LaloData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static LaloData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static LaloData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static LaloData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(LaloData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            LaloData, Builder> implements
          // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData)
          LaloDataOrBuilder {
        // Construct using com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBeanOuterClass.UploadLaLoRequestBean.LaloData.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional string bssid = 1;</code>
         */
        public String getBssid() {
          return instance.getBssid();
        }
        /**
         * <code>optional string bssid = 1;</code>
         */
        public com.google.protobuf.ByteString
            getBssidBytes() {
          return instance.getBssidBytes();
        }
        /**
         * <code>optional string bssid = 1;</code>
         */
        public Builder setBssid(
            String value) {
          copyOnWrite();
          instance.setBssid(value);
          return this;
        }
        /**
         * <code>optional string bssid = 1;</code>
         */
        public Builder clearBssid() {
          copyOnWrite();
          instance.clearBssid();
          return this;
        }
        /**
         * <code>optional string bssid = 1;</code>
         */
        public Builder setBssidBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setBssidBytes(value);
          return this;
        }

        /**
         * <code>optional string secLevel = 2;</code>
         */
        public String getSecLevel() {
          return instance.getSecLevel();
        }
        /**
         * <code>optional string secLevel = 2;</code>
         */
        public com.google.protobuf.ByteString
            getSecLevelBytes() {
          return instance.getSecLevelBytes();
        }
        /**
         * <code>optional string secLevel = 2;</code>
         */
        public Builder setSecLevel(
            String value) {
          copyOnWrite();
          instance.setSecLevel(value);
          return this;
        }
        /**
         * <code>optional string secLevel = 2;</code>
         */
        public Builder clearSecLevel() {
          copyOnWrite();
          instance.clearSecLevel();
          return this;
        }
        /**
         * <code>optional string secLevel = 2;</code>
         */
        public Builder setSecLevelBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setSecLevelBytes(value);
          return this;
        }

        /**
         * <code>optional string la = 3;</code>
         */
        public String getLa() {
          return instance.getLa();
        }
        /**
         * <code>optional string la = 3;</code>
         */
        public com.google.protobuf.ByteString
            getLaBytes() {
          return instance.getLaBytes();
        }
        /**
         * <code>optional string la = 3;</code>
         */
        public Builder setLa(
            String value) {
          copyOnWrite();
          instance.setLa(value);
          return this;
        }
        /**
         * <code>optional string la = 3;</code>
         */
        public Builder clearLa() {
          copyOnWrite();
          instance.clearLa();
          return this;
        }
        /**
         * <code>optional string la = 3;</code>
         */
        public Builder setLaBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setLaBytes(value);
          return this;
        }

        /**
         * <code>optional string lo = 4;</code>
         */
        public String getLo() {
          return instance.getLo();
        }
        /**
         * <code>optional string lo = 4;</code>
         */
        public com.google.protobuf.ByteString
            getLoBytes() {
          return instance.getLoBytes();
        }
        /**
         * <code>optional string lo = 4;</code>
         */
        public Builder setLo(
            String value) {
          copyOnWrite();
          instance.setLo(value);
          return this;
        }
        /**
         * <code>optional string lo = 4;</code>
         */
        public Builder clearLo() {
          copyOnWrite();
          instance.clearLo();
          return this;
        }
        /**
         * <code>optional string lo = 4;</code>
         */
        public Builder setLoBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setLoBytes(value);
          return this;
        }

        /**
         * <code>optional string mapSP = 5;</code>
         */
        public String getMapSP() {
          return instance.getMapSP();
        }
        /**
         * <code>optional string mapSP = 5;</code>
         */
        public com.google.protobuf.ByteString
            getMapSPBytes() {
          return instance.getMapSPBytes();
        }
        /**
         * <code>optional string mapSP = 5;</code>
         */
        public Builder setMapSP(
            String value) {
          copyOnWrite();
          instance.setMapSP(value);
          return this;
        }
        /**
         * <code>optional string mapSP = 5;</code>
         */
        public Builder clearMapSP() {
          copyOnWrite();
          instance.clearMapSP();
          return this;
        }
        /**
         * <code>optional string mapSP = 5;</code>
         */
        public Builder setMapSPBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setMapSPBytes(value);
          return this;
        }

        /**
         * <code>optional string rssi = 6;</code>
         */
        public String getRssi() {
          return instance.getRssi();
        }
        /**
         * <code>optional string rssi = 6;</code>
         */
        public com.google.protobuf.ByteString
            getRssiBytes() {
          return instance.getRssiBytes();
        }
        /**
         * <code>optional string rssi = 6;</code>
         */
        public Builder setRssi(
            String value) {
          copyOnWrite();
          instance.setRssi(value);
          return this;
        }
        /**
         * <code>optional string rssi = 6;</code>
         */
        public Builder clearRssi() {
          copyOnWrite();
          instance.clearRssi();
          return this;
        }
        /**
         * <code>optional string rssi = 6;</code>
         */
        public Builder setRssiBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setRssiBytes(value);
          return this;
        }

        /**
         * <code>optional string ls = 7;</code>
         */
        public String getLs() {
          return instance.getLs();
        }
        /**
         * <code>optional string ls = 7;</code>
         */
        public com.google.protobuf.ByteString
            getLsBytes() {
          return instance.getLsBytes();
        }
        /**
         * <code>optional string ls = 7;</code>
         */
        public Builder setLs(
            String value) {
          copyOnWrite();
          instance.setLs(value);
          return this;
        }
        /**
         * <code>optional string ls = 7;</code>
         */
        public Builder clearLs() {
          copyOnWrite();
          instance.clearLs();
          return this;
        }
        /**
         * <code>optional string ls = 7;</code>
         */
        public Builder setLsBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setLsBytes(value);
          return this;
        }

        /**
         * <code>optional string ts = 8;</code>
         */
        public String getTs() {
          return instance.getTs();
        }
        /**
         * <code>optional string ts = 8;</code>
         */
        public com.google.protobuf.ByteString
            getTsBytes() {
          return instance.getTsBytes();
        }
        /**
         * <code>optional string ts = 8;</code>
         */
        public Builder setTs(
            String value) {
          copyOnWrite();
          instance.setTs(value);
          return this;
        }
        /**
         * <code>optional string ts = 8;</code>
         */
        public Builder clearTs() {
          copyOnWrite();
          instance.clearTs();
          return this;
        }
        /**
         * <code>optional string ts = 8;</code>
         */
        public Builder setTsBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setTsBytes(value);
          return this;
        }

        /**
         * <code>optional string sn = 9;</code>
         */
        public String getSn() {
          return instance.getSn();
        }
        /**
         * <code>optional string sn = 9;</code>
         */
        public com.google.protobuf.ByteString
            getSnBytes() {
          return instance.getSnBytes();
        }
        /**
         * <code>optional string sn = 9;</code>
         */
        public Builder setSn(
            String value) {
          copyOnWrite();
          instance.setSn(value);
          return this;
        }
        /**
         * <code>optional string sn = 9;</code>
         */
        public Builder clearSn() {
          copyOnWrite();
          instance.clearSn();
          return this;
        }
        /**
         * <code>optional string sn = 9;</code>
         */
        public Builder setSnBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setSnBytes(value);
          return this;
        }

        /**
         * <code>optional string lac = 10;</code>
         */
        public String getLac() {
          return instance.getLac();
        }
        /**
         * <code>optional string lac = 10;</code>
         */
        public com.google.protobuf.ByteString
            getLacBytes() {
          return instance.getLacBytes();
        }
        /**
         * <code>optional string lac = 10;</code>
         */
        public Builder setLac(
            String value) {
          copyOnWrite();
          instance.setLac(value);
          return this;
        }
        /**
         * <code>optional string lac = 10;</code>
         */
        public Builder clearLac() {
          copyOnWrite();
          instance.clearLac();
          return this;
        }
        /**
         * <code>optional string lac = 10;</code>
         */
        public Builder setLacBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setLacBytes(value);
          return this;
        }

        /**
         * <code>optional string cid = 11;</code>
         */
        public String getCid() {
          return instance.getCid();
        }
        /**
         * <code>optional string cid = 11;</code>
         */
        public com.google.protobuf.ByteString
            getCidBytes() {
          return instance.getCidBytes();
        }
        /**
         * <code>optional string cid = 11;</code>
         */
        public Builder setCid(
            String value) {
          copyOnWrite();
          instance.setCid(value);
          return this;
        }
        /**
         * <code>optional string cid = 11;</code>
         */
        public Builder clearCid() {
          copyOnWrite();
          instance.clearCid();
          return this;
        }
        /**
         * <code>optional string cid = 11;</code>
         */
        public Builder setCidBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setCidBytes(value);
          return this;
        }

        /**
         * <code>optional string ssid = 12;</code>
         */
        public String getSsid() {
          return instance.getSsid();
        }
        /**
         * <code>optional string ssid = 12;</code>
         */
        public com.google.protobuf.ByteString
            getSsidBytes() {
          return instance.getSsidBytes();
        }
        /**
         * <code>optional string ssid = 12;</code>
         */
        public Builder setSsid(
            String value) {
          copyOnWrite();
          instance.setSsid(value);
          return this;
        }
        /**
         * <code>optional string ssid = 12;</code>
         */
        public Builder clearSsid() {
          copyOnWrite();
          instance.clearSsid();
          return this;
        }
        /**
         * <code>optional string ssid = 12;</code>
         */
        public Builder setSsidBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setSsidBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData)
      }
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new LaloData();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            LaloData other = (LaloData) arg1;
            bssid_ = visitor.visitString(!bssid_.isEmpty(), bssid_,
                !other.bssid_.isEmpty(), other.bssid_);
            secLevel_ = visitor.visitString(!secLevel_.isEmpty(), secLevel_,
                !other.secLevel_.isEmpty(), other.secLevel_);
            la_ = visitor.visitString(!la_.isEmpty(), la_,
                !other.la_.isEmpty(), other.la_);
            lo_ = visitor.visitString(!lo_.isEmpty(), lo_,
                !other.lo_.isEmpty(), other.lo_);
            mapSP_ = visitor.visitString(!mapSP_.isEmpty(), mapSP_,
                !other.mapSP_.isEmpty(), other.mapSP_);
            rssi_ = visitor.visitString(!rssi_.isEmpty(), rssi_,
                !other.rssi_.isEmpty(), other.rssi_);
            ls_ = visitor.visitString(!ls_.isEmpty(), ls_,
                !other.ls_.isEmpty(), other.ls_);
            ts_ = visitor.visitString(!ts_.isEmpty(), ts_,
                !other.ts_.isEmpty(), other.ts_);
            sn_ = visitor.visitString(!sn_.isEmpty(), sn_,
                !other.sn_.isEmpty(), other.sn_);
            lac_ = visitor.visitString(!lac_.isEmpty(), lac_,
                !other.lac_.isEmpty(), other.lac_);
            cid_ = visitor.visitString(!cid_.isEmpty(), cid_,
                !other.cid_.isEmpty(), other.cid_);
            ssid_ = visitor.visitString(!ssid_.isEmpty(), ssid_,
                !other.ssid_.isEmpty(), other.ssid_);
            if (visitor == MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readStringRequireUtf8();

                    bssid_ = s;
                    break;
                  }
                  case 18: {
                    String s = input.readStringRequireUtf8();

                    secLevel_ = s;
                    break;
                  }
                  case 26: {
                    String s = input.readStringRequireUtf8();

                    la_ = s;
                    break;
                  }
                  case 34: {
                    String s = input.readStringRequireUtf8();

                    lo_ = s;
                    break;
                  }
                  case 42: {
                    String s = input.readStringRequireUtf8();

                    mapSP_ = s;
                    break;
                  }
                  case 50: {
                    String s = input.readStringRequireUtf8();

                    rssi_ = s;
                    break;
                  }
                  case 58: {
                    String s = input.readStringRequireUtf8();

                    ls_ = s;
                    break;
                  }
                  case 66: {
                    String s = input.readStringRequireUtf8();

                    ts_ = s;
                    break;
                  }
                  case 74: {
                    String s = input.readStringRequireUtf8();

                    sn_ = s;
                    break;
                  }
                  case 82: {
                    String s = input.readStringRequireUtf8();

                    lac_ = s;
                    break;
                  }
                  case 90: {
                    String s = input.readStringRequireUtf8();

                    cid_ = s;
                    break;
                  }
                  case 98: {
                    String s = input.readStringRequireUtf8();

                    ssid_ = s;
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (LaloData.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData)
      private static final LaloData DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new LaloData();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static LaloData getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<LaloData> PARSER;

      public static com.google.protobuf.Parser<LaloData> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int LALODATA_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<LaloData> laloData_;
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    public java.util.List<LaloData> getLaloDataList() {
      return laloData_;
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    public java.util.List<? extends LaloDataOrBuilder>
        getLaloDataOrBuilderList() {
      return laloData_;
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    public int getLaloDataCount() {
      return laloData_.size();
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    public LaloData getLaloData(int index) {
      return laloData_.get(index);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    public LaloDataOrBuilder getLaloDataOrBuilder(
        int index) {
      return laloData_.get(index);
    }
    private void ensureLaloDataIsMutable() {
      if (!laloData_.isModifiable()) {
        laloData_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(laloData_);
       }
    }

    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void setLaloData(
        int index, LaloData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLaloDataIsMutable();
      laloData_.set(index, value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void setLaloData(
        int index, LaloData.Builder builderForValue) {
      ensureLaloDataIsMutable();
      laloData_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void addLaloData(LaloData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLaloDataIsMutable();
      laloData_.add(value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void addLaloData(
        int index, LaloData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLaloDataIsMutable();
      laloData_.add(index, value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void addLaloData(
        LaloData.Builder builderForValue) {
      ensureLaloDataIsMutable();
      laloData_.add(builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void addLaloData(
        int index, LaloData.Builder builderForValue) {
      ensureLaloDataIsMutable();
      laloData_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void addAllLaloData(
        Iterable<? extends LaloData> values) {
      ensureLaloDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, laloData_);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void clearLaloData() {
      laloData_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
     */
    private void removeLaloData(int index) {
      ensureLaloDataIsMutable();
      laloData_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < laloData_.size(); i++) {
        output.writeMessage(1, laloData_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < laloData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, laloData_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static UploadLaLoRequestBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UploadLaLoRequestBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UploadLaLoRequestBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UploadLaLoRequestBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UploadLaLoRequestBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UploadLaLoRequestBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UploadLaLoRequestBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static UploadLaLoRequestBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UploadLaLoRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UploadLaLoRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UploadLaLoRequestBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UploadLaLoRequestBean, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean)
        UploadLaLoRequestBeanOrBuilder {
      // Construct using com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBeanOuterClass.UploadLaLoRequestBean.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public java.util.List<LaloData> getLaloDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getLaloDataList());
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public int getLaloDataCount() {
        return instance.getLaloDataCount();
      }/**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public LaloData getLaloData(int index) {
        return instance.getLaloData(index);
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder setLaloData(
          int index, LaloData value) {
        copyOnWrite();
        instance.setLaloData(index, value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder setLaloData(
          int index, LaloData.Builder builderForValue) {
        copyOnWrite();
        instance.setLaloData(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder addLaloData(LaloData value) {
        copyOnWrite();
        instance.addLaloData(value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder addLaloData(
          int index, LaloData value) {
        copyOnWrite();
        instance.addLaloData(index, value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder addLaloData(
          LaloData.Builder builderForValue) {
        copyOnWrite();
        instance.addLaloData(builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder addLaloData(
          int index, LaloData.Builder builderForValue) {
        copyOnWrite();
        instance.addLaloData(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder addAllLaloData(
          Iterable<? extends LaloData> values) {
        copyOnWrite();
        instance.addAllLaloData(values);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder clearLaloData() {
        copyOnWrite();
        instance.clearLaloData();
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean.LaloData laloData = 1;</code>
       */
      public Builder removeLaloData(int index) {
        copyOnWrite();
        instance.removeLaloData(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UploadLaLoRequestBean();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          laloData_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          UploadLaLoRequestBean other = (UploadLaLoRequestBean) arg1;
          laloData_= visitor.visitList(laloData_, other.laloData_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!laloData_.isModifiable()) {
                    laloData_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(laloData_);
                  }
                  laloData_.add(
                      input.readMessage(LaloData.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (UploadLaLoRequestBean.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.uploadlalo.protobuf.UploadLaLoRequestBean)
    private static final UploadLaLoRequestBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UploadLaLoRequestBean();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static UploadLaLoRequestBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UploadLaLoRequestBean> PARSER;

    public static com.google.protobuf.Parser<UploadLaLoRequestBean> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
