// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.caizenghui;

public final class DCRequest {
    private DCRequest() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface DCRequestBeanOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.halo.dc.web.cmd.dc.protobuf.DCRequestBean)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional string dcType = 1;</code>
         */
        String getDcType();

        /**
         * <code>optional string dcType = 1;</code>
         */
        com.google.protobuf.ByteString getDcTypeBytes();

        /**
         * <code>optional string msg = 2;</code>
         */
        String getMsg();

        /**
         * <code>optional string msg = 2;</code>
         */
        com.google.protobuf.ByteString getMsgBytes();
    }

    /**
     * Protobuf type {@code com.halo.dc.web.cmd.dc.protobuf.DCRequestBean}
     */
    public static final class DCRequestBean
            extends com.google.protobuf.GeneratedMessageLite<DCRequestBean, DCRequestBean.Builder> implements
            // @@protoc_insertion_point(message_implements:com.halo.dc.web.cmd.dc.protobuf.DCRequestBean)
            DCRequestBeanOrBuilder {
        private DCRequestBean() {
            dcType_ = "";
            msg_ = "";
        }

        public static final int DCTYPE_FIELD_NUMBER = 1;
        private String dcType_;

        /**
         * <code>optional string dcType = 1;</code>
         */
        public String getDcType() {
            return dcType_;
        }

        /**
         * <code>optional string dcType = 1;</code>
         */
        public com.google.protobuf.ByteString getDcTypeBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(dcType_);
        }

        /**
         * <code>optional string dcType = 1;</code>
         */
        private void setDcType(String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            dcType_ = value;
        }

        /**
         * <code>optional string dcType = 1;</code>
         */
        private void clearDcType() {

            dcType_ = getDefaultInstance().getDcType();
        }

        /**
         * <code>optional string dcType = 1;</code>
         */
        private void setDcTypeBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            dcType_ = value.toStringUtf8();
        }

        public static final int MSG_FIELD_NUMBER = 2;
        private String msg_;

        /**
         * <code>optional string msg = 2;</code>
         */
        public String getMsg() {
            return msg_;
        }

        /**
         * <code>optional string msg = 2;</code>
         */
        public com.google.protobuf.ByteString getMsgBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(msg_);
        }

        /**
         * <code>optional string msg = 2;</code>
         */
        private void setMsg(String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msg_ = value;
        }

        /**
         * <code>optional string msg = 2;</code>
         */
        private void clearMsg() {

            msg_ = getDefaultInstance().getMsg();
        }

        /**
         * <code>optional string msg = 2;</code>
         */
        private void setMsgBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            msg_ = value.toStringUtf8();
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!dcType_.isEmpty()) {
                output.writeString(1, getDcType());
            }
            if (!msg_.isEmpty()) {
                output.writeString(2, getMsg());
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!dcType_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeStringSize(1, getDcType());
            }
            if (!msg_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeStringSize(2, getMsg());
            }
            memoizedSerializedSize = size;
            return size;
        }

        public static DCRequestBean parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
        }

        public static DCRequestBean parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static DCRequestBean parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
        }

        public static DCRequestBean parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static DCRequestBean parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
        }

        public static DCRequestBean parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static DCRequestBean parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static DCRequestBean parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static DCRequestBean parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
        }

        public static DCRequestBean parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(DCRequestBean prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * Protobuf type {@code com.halo.dc.web.cmd.dc.protobuf.DCRequestBean}
         */
        public static final class Builder
                extends com.google.protobuf.GeneratedMessageLite.Builder<DCRequestBean, Builder> implements
                // @@protoc_insertion_point(builder_implements:com.halo.dc.web.cmd.dc.protobuf.DCRequestBean)
                DCRequestBeanOrBuilder {
            // Construct using
            // com.example.caizenghui.DCRequest.DCRequestBean.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }

            /**
             * <code>optional string dcType = 1;</code>
             */
            public String getDcType() {
                return instance.getDcType();
            }

            /**
             * <code>optional string dcType = 1;</code>
             */
            public com.google.protobuf.ByteString getDcTypeBytes() {
                return instance.getDcTypeBytes();
            }

            /**
             * <code>optional string dcType = 1;</code>
             */
            public Builder setDcType(String value) {
                copyOnWrite();
                instance.setDcType(value);
                return this;
            }

            /**
             * <code>optional string dcType = 1;</code>
             */
            public Builder clearDcType() {
                copyOnWrite();
                instance.clearDcType();
                return this;
            }

            /**
             * <code>optional string dcType = 1;</code>
             */
            public Builder setDcTypeBytes(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setDcTypeBytes(value);
                return this;
            }

            /**
             * <code>optional string msg = 2;</code>
             */
            public String getMsg() {
                return instance.getMsg();
            }

            /**
             * <code>optional string msg = 2;</code>
             */
            public com.google.protobuf.ByteString getMsgBytes() {
                return instance.getMsgBytes();
            }

            /**
             * <code>optional string msg = 2;</code>
             */
            public Builder setMsg(String value) {
                copyOnWrite();
                instance.setMsg(value);
                return this;
            }

            /**
             * <code>optional string msg = 2;</code>
             */
            public Builder clearMsg() {
                copyOnWrite();
                instance.clearMsg();
                return this;
            }

            /**
             * <code>optional string msg = 2;</code>
             */
            public Builder setMsgBytes(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setMsgBytes(value);
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.halo.dc.web.cmd.dc.protobuf.DCRequestBean)
        }

        protected final Object dynamicMethod(MethodToInvoke method, Object arg0, Object arg1) {
            switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new DCRequestBean();
            }
            case IS_INITIALIZED: {
                return DEFAULT_INSTANCE;
            }
            case MAKE_IMMUTABLE: {
                return null;
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case VISIT: {
                Visitor visitor = (Visitor) arg0;
                DCRequestBean other = (DCRequestBean) arg1;
                dcType_ = visitor.visitString(!dcType_.isEmpty(), dcType_, !other.dcType_.isEmpty(), other.dcType_);
                msg_ = visitor.visitString(!msg_.isEmpty(), msg_, !other.msg_.isEmpty(), other.msg_);
                if (visitor == MergeFromVisitor.INSTANCE) {
                }
                return this;
            }
            case MERGE_FROM_STREAM: {
                com.google.protobuf.CodedInputStream input = (com.google.protobuf.CodedInputStream) arg0;
                com.google.protobuf.ExtensionRegistryLite extensionRegistry = (com.google.protobuf.ExtensionRegistryLite) arg1;
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            dcType_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw new RuntimeException(e.setUnfinishedMessage(this));
                } catch (java.io.IOException e) {
                    throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                            .setUnfinishedMessage(this));
                } finally {
                }
            }
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                if (PARSER == null) {
                    synchronized (DCRequestBean.class) {
                        if (PARSER == null) {
                            PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                        }
                    }
                }
                return PARSER;
            }
            }
            throw new UnsupportedOperationException();
        }

        // @@protoc_insertion_point(class_scope:com.halo.dc.web.cmd.dc.protobuf.DCRequestBean)
        private static final DCRequestBean DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new DCRequestBean();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static DCRequestBean getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<DCRequestBean> PARSER;

        public static com.google.protobuf.Parser<DCRequestBean> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
