// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApQueryPwdResponseModel.proto

package com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf;

public final class ApQueryPwdResponseModelOuterClass {
  private ApQueryPwdResponseModelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApQueryPwdResponseModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    java.util.List<ApQueryPwdResponseModel.Mapfield>
        getApsList();
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    ApQueryPwdResponseModel.Mapfield getAps(int index);
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    int getApsCount();

    /**
     * <code>optional string s = 2;</code>
     */
    String getS();
    /**
     * <code>optional string s = 2;</code>
     */
    com.google.protobuf.ByteString
        getSBytes();

    /**
     * <code>optional sint32 topn = 3;</code>
     */
    int getTopn();

    /**
     * <code>optional string qid = 4;</code>
     */
    String getQid();
    /**
     * <code>optional string qid = 4;</code>
     */
    com.google.protobuf.ByteString
        getQidBytes();

    /**
     * <code>optional string sysTime = 5;</code>
     */
    String getSysTime();
    /**
     * <code>optional string sysTime = 5;</code>
     */
    com.google.protobuf.ByteString
        getSysTimeBytes();
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel}
   */
  public  static final class ApQueryPwdResponseModel extends
      com.google.protobuf.GeneratedMessageLite<
          ApQueryPwdResponseModel, ApQueryPwdResponseModel.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel)
      ApQueryPwdResponseModelOrBuilder {
    private ApQueryPwdResponseModel() {
      aps_ = emptyProtobufList();
      s_ = "";
      qid_ = "";
      sysTime_ = "";
    }
    public interface MapfieldOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      int getMfCount();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      boolean containsMf(
              String key);
      /**
       * Use {@link #getMfMap()} instead.
       */
      @Deprecated
      java.util.Map<String, String>
      getMf();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      java.util.Map<String, String>
      getMfMap();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      String getMfOrDefault(
              String key,
              String defaultValue);
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      String getMfOrThrow(
              String key);
    }
    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield}
     */
    public  static final class Mapfield extends
        com.google.protobuf.GeneratedMessageLite<
            Mapfield, Mapfield.Builder> implements
        // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield)
        MapfieldOrBuilder {
      private Mapfield() {
      }
      public static final int MF_FIELD_NUMBER = 1;
      private static final class MfDefaultEntryHolder {
        static final com.google.protobuf.MapEntryLite<
            String, String> defaultEntry =
                com.google.protobuf.MapEntryLite
                .<String, String>newDefaultInstance(
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "");
      }
      private com.google.protobuf.MapFieldLite<
          String, String> mf_ =
              com.google.protobuf.MapFieldLite.emptyMapField();
      private com.google.protobuf.MapFieldLite<String, String>
      internalGetMf() {
        return mf_;
      }
      private com.google.protobuf.MapFieldLite<String, String>
      internalGetMutableMf() {
        if (!mf_.isMutable()) {
          mf_ = mf_.mutableCopy();
        }
        return mf_;
      }

      public int getMfCount() {
        return internalGetMf().size();
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public boolean containsMf(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMf().containsKey(key);
      }
      /**
       * Use {@link #getMfMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getMf() {
        return getMfMap();
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public java.util.Map<String, String> getMfMap() {
        return java.util.Collections.unmodifiableMap(
            internalGetMf());
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public String getMfOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMf();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public String getMfOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMf();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      private java.util.Map<String, String>
      getMutableMfMap() {
        return internalGetMutableMf();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (java.util.Map.Entry<String, String> entry
             : internalGetMf().entrySet()) {
          MfDefaultEntryHolder.defaultEntry.serializeTo(
              output, 1, entry.getKey(), entry.getValue());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<String, String> entry
             : internalGetMf().entrySet()) {
          size += MfDefaultEntryHolder.defaultEntry.computeMessageSize(
            1, entry.getKey(), entry.getValue());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static Mapfield parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Mapfield parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Mapfield parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Mapfield parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Mapfield parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static Mapfield parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static Mapfield parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static Mapfield parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static Mapfield parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static Mapfield parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Mapfield prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            Mapfield, Builder> implements
          // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield)
          MapfieldOrBuilder {
        // Construct using com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModelOuterClass.ApQueryPwdResponseModel.Mapfield.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }



        public int getMfCount() {
          return instance.getMfMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public boolean containsMf(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          return instance.getMfMap().containsKey(key);
        }

        public Builder clearMf() {
          copyOnWrite();
          instance.getMutableMfMap().clear();
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public Builder removeMf(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          copyOnWrite();
          instance.getMutableMfMap().remove(key);
          return this;
        }
        /**
         * Use {@link #getMfMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, String> getMf() {
          return getMfMap();
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public java.util.Map<String, String> getMfMap() {
          return java.util.Collections.unmodifiableMap(
              instance.getMfMap());
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public String getMfOrDefault(
            String key,
            String defaultValue) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, String> map =
              instance.getMfMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public String getMfOrThrow(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, String> map =
              instance.getMfMap();
          if (!map.containsKey(key)) {
            throw new IllegalArgumentException();
          }
          return map.get(key);
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public Builder putMf(
            String key,
            String value) {
          if (key == null) { throw new NullPointerException(); }
          if (value == null) { throw new NullPointerException(); }
          copyOnWrite();
          instance.getMutableMfMap().put(key, value);
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public Builder putAllMf(
            java.util.Map<String, String> values) {
          copyOnWrite();
          instance.getMutableMfMap().putAll(values);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield)
      }
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new Mapfield();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            mf_.makeImmutable();
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            Mapfield other = (Mapfield) arg1;
            mf_ = visitor.visitMap(
                mf_, other.internalGetMf());
            if (visitor == MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    if (!mf_.isMutable()) {
                      mf_ = mf_.mutableCopy();
                    }
                    MfDefaultEntryHolder.defaultEntry.parseInto(mf_, input, extensionRegistry);  break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (Mapfield.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield)
      private static final Mapfield DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Mapfield();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static Mapfield getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Mapfield> PARSER;

      public static com.google.protobuf.Parser<Mapfield> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int APS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Mapfield> aps_;
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    public java.util.List<Mapfield> getApsList() {
      return aps_;
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    public java.util.List<? extends MapfieldOrBuilder>
        getApsOrBuilderList() {
      return aps_;
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    public int getApsCount() {
      return aps_.size();
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    public Mapfield getAps(int index) {
      return aps_.get(index);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    public MapfieldOrBuilder getApsOrBuilder(
        int index) {
      return aps_.get(index);
    }
    private void ensureApsIsMutable() {
      if (!aps_.isModifiable()) {
        aps_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(aps_);
       }
    }

    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void setAps(
        int index, Mapfield value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureApsIsMutable();
      aps_.set(index, value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void setAps(
        int index, Mapfield.Builder builderForValue) {
      ensureApsIsMutable();
      aps_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void addAps(Mapfield value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureApsIsMutable();
      aps_.add(value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void addAps(
        int index, Mapfield value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureApsIsMutable();
      aps_.add(index, value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void addAps(
        Mapfield.Builder builderForValue) {
      ensureApsIsMutable();
      aps_.add(builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void addAps(
        int index, Mapfield.Builder builderForValue) {
      ensureApsIsMutable();
      aps_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void addAllAps(
        Iterable<? extends Mapfield> values) {
      ensureApsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, aps_);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void clearAps() {
      aps_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
     */
    private void removeAps(int index) {
      ensureApsIsMutable();
      aps_.remove(index);
    }

    public static final int S_FIELD_NUMBER = 2;
    private String s_;
    /**
     * <code>optional string s = 2;</code>
     */
    public String getS() {
      return s_;
    }
    /**
     * <code>optional string s = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(s_);
    }
    /**
     * <code>optional string s = 2;</code>
     */
    private void setS(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      s_ = value;
    }
    /**
     * <code>optional string s = 2;</code>
     */
    private void clearS() {
      
      s_ = getDefaultInstance().getS();
    }
    /**
     * <code>optional string s = 2;</code>
     */
    private void setSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      s_ = value.toStringUtf8();
    }

    public static final int TOPN_FIELD_NUMBER = 3;
    private int topn_;
    /**
     * <code>optional sint32 topn = 3;</code>
     */
    public int getTopn() {
      return topn_;
    }
    /**
     * <code>optional sint32 topn = 3;</code>
     */
    private void setTopn(int value) {
      
      topn_ = value;
    }
    /**
     * <code>optional sint32 topn = 3;</code>
     */
    private void clearTopn() {
      
      topn_ = 0;
    }

    public static final int QID_FIELD_NUMBER = 4;
    private String qid_;
    /**
     * <code>optional string qid = 4;</code>
     */
    public String getQid() {
      return qid_;
    }
    /**
     * <code>optional string qid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getQidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(qid_);
    }
    /**
     * <code>optional string qid = 4;</code>
     */
    private void setQid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      qid_ = value;
    }
    /**
     * <code>optional string qid = 4;</code>
     */
    private void clearQid() {
      
      qid_ = getDefaultInstance().getQid();
    }
    /**
     * <code>optional string qid = 4;</code>
     */
    private void setQidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      qid_ = value.toStringUtf8();
    }

    public static final int SYSTIME_FIELD_NUMBER = 5;
    private String sysTime_;
    /**
     * <code>optional string sysTime = 5;</code>
     */
    public String getSysTime() {
      return sysTime_;
    }
    /**
     * <code>optional string sysTime = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSysTimeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sysTime_);
    }
    /**
     * <code>optional string sysTime = 5;</code>
     */
    private void setSysTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sysTime_ = value;
    }
    /**
     * <code>optional string sysTime = 5;</code>
     */
    private void clearSysTime() {
      
      sysTime_ = getDefaultInstance().getSysTime();
    }
    /**
     * <code>optional string sysTime = 5;</code>
     */
    private void setSysTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sysTime_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < aps_.size(); i++) {
        output.writeMessage(1, aps_.get(i));
      }
      if (!s_.isEmpty()) {
        output.writeString(2, getS());
      }
      if (topn_ != 0) {
        output.writeSInt32(3, topn_);
      }
      if (!qid_.isEmpty()) {
        output.writeString(4, getQid());
      }
      if (!sysTime_.isEmpty()) {
        output.writeString(5, getSysTime());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < aps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, aps_.get(i));
      }
      if (!s_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getS());
      }
      if (topn_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, topn_);
      }
      if (!qid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getQid());
      }
      if (!sysTime_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getSysTime());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApQueryPwdResponseModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApQueryPwdResponseModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApQueryPwdResponseModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApQueryPwdResponseModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApQueryPwdResponseModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApQueryPwdResponseModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApQueryPwdResponseModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApQueryPwdResponseModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApQueryPwdResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApQueryPwdResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApQueryPwdResponseModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApQueryPwdResponseModel, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel)
        ApQueryPwdResponseModelOrBuilder {
      // Construct using com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModelOuterClass.ApQueryPwdResponseModel.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public java.util.List<Mapfield> getApsList() {
        return java.util.Collections.unmodifiableList(
            instance.getApsList());
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public int getApsCount() {
        return instance.getApsCount();
      }/**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Mapfield getAps(int index) {
        return instance.getAps(index);
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder setAps(
          int index, Mapfield value) {
        copyOnWrite();
        instance.setAps(index, value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder setAps(
          int index, Mapfield.Builder builderForValue) {
        copyOnWrite();
        instance.setAps(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder addAps(Mapfield value) {
        copyOnWrite();
        instance.addAps(value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder addAps(
          int index, Mapfield value) {
        copyOnWrite();
        instance.addAps(index, value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder addAps(
          Mapfield.Builder builderForValue) {
        copyOnWrite();
        instance.addAps(builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder addAps(
          int index, Mapfield.Builder builderForValue) {
        copyOnWrite();
        instance.addAps(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder addAllAps(
          Iterable<? extends Mapfield> values) {
        copyOnWrite();
        instance.addAllAps(values);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder clearAps() {
        copyOnWrite();
        instance.clearAps();
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel.Mapfield aps = 1;</code>
       */
      public Builder removeAps(int index) {
        copyOnWrite();
        instance.removeAps(index);
        return this;
      }

      /**
       * <code>optional string s = 2;</code>
       */
      public String getS() {
        return instance.getS();
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSBytes() {
        return instance.getSBytes();
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public Builder setS(
          String value) {
        copyOnWrite();
        instance.setS(value);
        return this;
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public Builder clearS() {
        copyOnWrite();
        instance.clearS();
        return this;
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public Builder setSBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSBytes(value);
        return this;
      }

      /**
       * <code>optional sint32 topn = 3;</code>
       */
      public int getTopn() {
        return instance.getTopn();
      }
      /**
       * <code>optional sint32 topn = 3;</code>
       */
      public Builder setTopn(int value) {
        copyOnWrite();
        instance.setTopn(value);
        return this;
      }
      /**
       * <code>optional sint32 topn = 3;</code>
       */
      public Builder clearTopn() {
        copyOnWrite();
        instance.clearTopn();
        return this;
      }

      /**
       * <code>optional string qid = 4;</code>
       */
      public String getQid() {
        return instance.getQid();
      }
      /**
       * <code>optional string qid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getQidBytes() {
        return instance.getQidBytes();
      }
      /**
       * <code>optional string qid = 4;</code>
       */
      public Builder setQid(
          String value) {
        copyOnWrite();
        instance.setQid(value);
        return this;
      }
      /**
       * <code>optional string qid = 4;</code>
       */
      public Builder clearQid() {
        copyOnWrite();
        instance.clearQid();
        return this;
      }
      /**
       * <code>optional string qid = 4;</code>
       */
      public Builder setQidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setQidBytes(value);
        return this;
      }

      /**
       * <code>optional string sysTime = 5;</code>
       */
      public String getSysTime() {
        return instance.getSysTime();
      }
      /**
       * <code>optional string sysTime = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSysTimeBytes() {
        return instance.getSysTimeBytes();
      }
      /**
       * <code>optional string sysTime = 5;</code>
       */
      public Builder setSysTime(
          String value) {
        copyOnWrite();
        instance.setSysTime(value);
        return this;
      }
      /**
       * <code>optional string sysTime = 5;</code>
       */
      public Builder clearSysTime() {
        copyOnWrite();
        instance.clearSysTime();
        return this;
      }
      /**
       * <code>optional string sysTime = 5;</code>
       */
      public Builder setSysTimeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSysTimeBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApQueryPwdResponseModel();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          aps_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApQueryPwdResponseModel other = (ApQueryPwdResponseModel) arg1;
          aps_= visitor.visitList(aps_, other.aps_);
          s_ = visitor.visitString(!s_.isEmpty(), s_,
              !other.s_.isEmpty(), other.s_);
          topn_ = visitor.visitInt(topn_ != 0, topn_,
              other.topn_ != 0, other.topn_);
          qid_ = visitor.visitString(!qid_.isEmpty(), qid_,
              !other.qid_.isEmpty(), other.qid_);
          sysTime_ = visitor.visitString(!sysTime_.isEmpty(), sysTime_,
              !other.sysTime_.isEmpty(), other.sysTime_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!aps_.isModifiable()) {
                    aps_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(aps_);
                  }
                  aps_.add(
                      input.readMessage(Mapfield.parser(), extensionRegistry));
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  s_ = s;
                  break;
                }
                case 24: {

                  topn_ = input.readSInt32();
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  qid_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  sysTime_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApQueryPwdResponseModel.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.querypwd.v3.protobuf.ApQueryPwdResponseModel)
    private static final ApQueryPwdResponseModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApQueryPwdResponseModel();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApQueryPwdResponseModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApQueryPwdResponseModel> PARSER;

    public static com.google.protobuf.Parser<ApQueryPwdResponseModel> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
