// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DropPrivateApRequestBean.proto

package com.halo.ap.web.cmd.privateap.drop.protobuf;

public final class DropPrivateApRequestBeanOuterClass {
  private DropPrivateApRequestBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DropPrivateApRequestBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.privateap.drop.protobuf.DropPrivateApRequestBean)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string ssid = 1;</code>
     */
    String getSsid();
    /**
     * <code>optional string ssid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSsidBytes();
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.privateap.drop.protobuf.DropPrivateApRequestBean}
   */
  public  static final class DropPrivateApRequestBean extends
      com.google.protobuf.GeneratedMessageLite<
          DropPrivateApRequestBean, DropPrivateApRequestBean.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.privateap.drop.protobuf.DropPrivateApRequestBean)
      DropPrivateApRequestBeanOrBuilder {
    private DropPrivateApRequestBean() {
      ssid_ = "";
    }
    public static final int SSID_FIELD_NUMBER = 1;
    private String ssid_;
    /**
     * <code>optional string ssid = 1;</code>
     */
    public String getSsid() {
      return ssid_;
    }
    /**
     * <code>optional string ssid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSsidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ssid_);
    }
    /**
     * <code>optional string ssid = 1;</code>
     */
    private void setSsid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ssid_ = value;
    }
    /**
     * <code>optional string ssid = 1;</code>
     */
    private void clearSsid() {
      
      ssid_ = getDefaultInstance().getSsid();
    }
    /**
     * <code>optional string ssid = 1;</code>
     */
    private void setSsidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ssid_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!ssid_.isEmpty()) {
        output.writeString(1, getSsid());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!ssid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSsid());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static DropPrivateApRequestBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static DropPrivateApRequestBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static DropPrivateApRequestBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static DropPrivateApRequestBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static DropPrivateApRequestBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static DropPrivateApRequestBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static DropPrivateApRequestBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static DropPrivateApRequestBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static DropPrivateApRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static DropPrivateApRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DropPrivateApRequestBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.privateap.drop.protobuf.DropPrivateApRequestBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          DropPrivateApRequestBean, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.privateap.drop.protobuf.DropPrivateApRequestBean)
        DropPrivateApRequestBeanOrBuilder {
      // Construct using com.halo.ap.web.cmd.privateap.drop.protobuf.DropPrivateApRequestBeanOuterClass.DropPrivateApRequestBean.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string ssid = 1;</code>
       */
      public String getSsid() {
        return instance.getSsid();
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        return instance.getSsidBytes();
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      public Builder setSsid(
          String value) {
        copyOnWrite();
        instance.setSsid(value);
        return this;
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      public Builder clearSsid() {
        copyOnWrite();
        instance.clearSsid();
        return this;
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      public Builder setSsidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSsidBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.privateap.drop.protobuf.DropPrivateApRequestBean)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new DropPrivateApRequestBean();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          DropPrivateApRequestBean other = (DropPrivateApRequestBean) arg1;
          ssid_ = visitor.visitString(!ssid_.isEmpty(), ssid_,
              !other.ssid_.isEmpty(), other.ssid_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  ssid_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (DropPrivateApRequestBean.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.privateap.drop.protobuf.DropPrivateApRequestBean)
    private static final DropPrivateApRequestBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DropPrivateApRequestBean();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static DropPrivateApRequestBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DropPrivateApRequestBean> PARSER;

    public static com.google.protobuf.Parser<DropPrivateApRequestBean> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
