// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApQueryOwnerListResponseModel.proto

package com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf;

public final class ApQueryOwnerListResponseModelOuterClass {
  private ApQueryOwnerListResponseModelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApQueryOwnerListResponseModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */
    int getApInfoCount();
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */
    boolean containsApInfo(
            String key);
    /**
     * Use {@link #getApInfoMap()} instead.
     */
    @Deprecated
    java.util.Map<String, ApQueryOwnerListResponseModel.MapField>
    getApInfo();
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */
    java.util.Map<String, ApQueryOwnerListResponseModel.MapField>
    getApInfoMap();
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */

    ApQueryOwnerListResponseModel.MapField getApInfoOrDefault(
            String key,
            ApQueryOwnerListResponseModel.MapField defaultValue);
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */

    ApQueryOwnerListResponseModel.MapField getApInfoOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel}
   */
  public  static final class ApQueryOwnerListResponseModel extends
      com.google.protobuf.GeneratedMessageLite<
          ApQueryOwnerListResponseModel, ApQueryOwnerListResponseModel.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel)
      ApQueryOwnerListResponseModelOrBuilder {
    private ApQueryOwnerListResponseModel() {
    }
    public interface MapFieldOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      int getMfCount();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      boolean containsMf(
              String key);
      /**
       * Use {@link #getMfMap()} instead.
       */
      @Deprecated
      java.util.Map<String, String>
      getMf();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      java.util.Map<String, String>
      getMfMap();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      String getMfOrDefault(
              String key,
              String defaultValue);
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      String getMfOrThrow(
              String key);
    }
    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField}
     */
    public  static final class MapField extends
        com.google.protobuf.GeneratedMessageLite<
            MapField, MapField.Builder> implements
        // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField)
        MapFieldOrBuilder {
      private MapField() {
      }
      public static final int MF_FIELD_NUMBER = 1;
      private static final class MfDefaultEntryHolder {
        static final com.google.protobuf.MapEntryLite<
            String, String> defaultEntry =
                com.google.protobuf.MapEntryLite
                .<String, String>newDefaultInstance(
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "");
      }
      private com.google.protobuf.MapFieldLite<
          String, String> mf_ =
              com.google.protobuf.MapFieldLite.emptyMapField();
      private com.google.protobuf.MapFieldLite<String, String>
      internalGetMf() {
        return mf_;
      }
      private com.google.protobuf.MapFieldLite<String, String>
      internalGetMutableMf() {
        if (!mf_.isMutable()) {
          mf_ = mf_.mutableCopy();
        }
        return mf_;
      }

      public int getMfCount() {
        return internalGetMf().size();
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public boolean containsMf(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMf().containsKey(key);
      }
      /**
       * Use {@link #getMfMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getMf() {
        return getMfMap();
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public java.util.Map<String, String> getMfMap() {
        return java.util.Collections.unmodifiableMap(
            internalGetMf());
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public String getMfOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMf();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public String getMfOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMf();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      private java.util.Map<String, String>
      getMutableMfMap() {
        return internalGetMutableMf();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (java.util.Map.Entry<String, String> entry
             : internalGetMf().entrySet()) {
          MfDefaultEntryHolder.defaultEntry.serializeTo(
              output, 1, entry.getKey(), entry.getValue());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<String, String> entry
             : internalGetMf().entrySet()) {
          size += MfDefaultEntryHolder.defaultEntry.computeMessageSize(
            1, entry.getKey(), entry.getValue());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static MapField parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static MapField parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static MapField parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static MapField parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static MapField parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static MapField parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static MapField parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static MapField parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static MapField parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static MapField parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MapField prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            MapField, Builder> implements
          // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField)
          MapFieldOrBuilder {
        // Construct using com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModelOuterClass.ApQueryOwnerListResponseModel.MapField.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }



        public int getMfCount() {
          return instance.getMfMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public boolean containsMf(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          return instance.getMfMap().containsKey(key);
        }

        public Builder clearMf() {
          copyOnWrite();
          instance.getMutableMfMap().clear();
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public Builder removeMf(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          copyOnWrite();
          instance.getMutableMfMap().remove(key);
          return this;
        }
        /**
         * Use {@link #getMfMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, String> getMf() {
          return getMfMap();
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public java.util.Map<String, String> getMfMap() {
          return java.util.Collections.unmodifiableMap(
              instance.getMfMap());
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public String getMfOrDefault(
            String key,
            String defaultValue) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, String> map =
              instance.getMfMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public String getMfOrThrow(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, String> map =
              instance.getMfMap();
          if (!map.containsKey(key)) {
            throw new IllegalArgumentException();
          }
          return map.get(key);
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public Builder putMf(
            String key,
            String value) {
          if (key == null) { throw new NullPointerException(); }
          if (value == null) { throw new NullPointerException(); }
          copyOnWrite();
          instance.getMutableMfMap().put(key, value);
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public Builder putAllMf(
            java.util.Map<String, String> values) {
          copyOnWrite();
          instance.getMutableMfMap().putAll(values);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField)
      }
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new MapField();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            mf_.makeImmutable();
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            MapField other = (MapField) arg1;
            mf_ = visitor.visitMap(
                mf_, other.internalGetMf());
            if (visitor == MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    if (!mf_.isMutable()) {
                      mf_ = mf_.mutableCopy();
                    }
                    MfDefaultEntryHolder.defaultEntry.parseInto(mf_, input, extensionRegistry);  break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (MapField.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField)
      private static final MapField DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MapField();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static MapField getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<MapField> PARSER;

      public static com.google.protobuf.Parser<MapField> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int APINFO_FIELD_NUMBER = 1;
    private static final class ApInfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          String, MapField> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<String, MapField>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  MapField.getDefaultInstance());
    }
    private com.google.protobuf.MapFieldLite<
        String, MapField> apInfo_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<String, MapField>
    internalGetApInfo() {
      return apInfo_;
    }
    private com.google.protobuf.MapFieldLite<String, MapField>
    internalGetMutableApInfo() {
      if (!apInfo_.isMutable()) {
        apInfo_ = apInfo_.mutableCopy();
      }
      return apInfo_;
    }

    public int getApInfoCount() {
      return internalGetApInfo().size();
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */

    public boolean containsApInfo(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetApInfo().containsKey(key);
    }
    /**
     * Use {@link #getApInfoMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, MapField> getApInfo() {
      return getApInfoMap();
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */

    public java.util.Map<String, MapField> getApInfoMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetApInfo());
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */

    public MapField getApInfoOrDefault(
        String key,
        MapField defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, MapField> map =
          internalGetApInfo();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */

    public MapField getApInfoOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, MapField> map =
          internalGetApInfo();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
     */
    private java.util.Map<String, MapField>
    getMutableApInfoMap() {
      return internalGetMutableApInfo();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<String, MapField> entry
           : internalGetApInfo().entrySet()) {
        ApInfoDefaultEntryHolder.defaultEntry.serializeTo(
            output, 1, entry.getKey(), entry.getValue());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<String, MapField> entry
           : internalGetApInfo().entrySet()) {
        size += ApInfoDefaultEntryHolder.defaultEntry.computeMessageSize(
          1, entry.getKey(), entry.getValue());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApQueryOwnerListResponseModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApQueryOwnerListResponseModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApQueryOwnerListResponseModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApQueryOwnerListResponseModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApQueryOwnerListResponseModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApQueryOwnerListResponseModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApQueryOwnerListResponseModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApQueryOwnerListResponseModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApQueryOwnerListResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApQueryOwnerListResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApQueryOwnerListResponseModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApQueryOwnerListResponseModel, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel)
        ApQueryOwnerListResponseModelOrBuilder {
      // Construct using com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModelOuterClass.ApQueryOwnerListResponseModel.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }



      public int getApInfoCount() {
        return instance.getApInfoMap().size();
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
       */

      public boolean containsApInfo(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return instance.getApInfoMap().containsKey(key);
      }

      public Builder clearApInfo() {
        copyOnWrite();
        instance.getMutableApInfoMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
       */

      public Builder removeApInfo(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        copyOnWrite();
        instance.getMutableApInfoMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getApInfoMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, MapField> getApInfo() {
        return getApInfoMap();
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
       */
      public java.util.Map<String, MapField> getApInfoMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getApInfoMap());
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
       */

      public MapField getApInfoOrDefault(
          String key,
          MapField defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, MapField> map =
            instance.getApInfoMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
       */

      public MapField getApInfoOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, MapField> map =
            instance.getApInfoMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
       */
      public Builder putApInfo(
          String key,
          MapField value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        copyOnWrite();
        instance.getMutableApInfoMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel.MapField&gt; apInfo = 1;</code>
       */
      public Builder putAllApInfo(
          java.util.Map<String, MapField> values) {
        copyOnWrite();
        instance.getMutableApInfoMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApQueryOwnerListResponseModel();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          apInfo_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApQueryOwnerListResponseModel other = (ApQueryOwnerListResponseModel) arg1;
          apInfo_ = visitor.visitMap(
              apInfo_, other.internalGetApInfo());
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!apInfo_.isMutable()) {
                    apInfo_ = apInfo_.mutableCopy();
                  }
                  ApInfoDefaultEntryHolder.defaultEntry.parseInto(apInfo_, input, extensionRegistry);  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApQueryOwnerListResponseModel.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.queryapownerlist.protobuf.ApQueryOwnerListResponseModel)
    private static final ApQueryOwnerListResponseModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApQueryOwnerListResponseModel();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApQueryOwnerListResponseModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApQueryOwnerListResponseModel> PARSER;

    public static com.google.protobuf.Parser<ApQueryOwnerListResponseModel> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
