// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThirdApQueryListRequestBean.proto

package com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf;

public final class ThirdApQueryListRequestBeanOuterClass {
  private ThirdApQueryListRequestBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ThirdApQueryListRequestBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    java.util.List<ThirdApQueryListRequestBean.Sb>
        getSbList();
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    ThirdApQueryListRequestBean.Sb getSb(int index);
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    int getSbCount();
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean}
   */
  public  static final class ThirdApQueryListRequestBean extends
      com.google.protobuf.GeneratedMessageLite<
          ThirdApQueryListRequestBean, ThirdApQueryListRequestBean.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean)
      ThirdApQueryListRequestBeanOrBuilder {
    private ThirdApQueryListRequestBean() {
      sb_ = emptyProtobufList();
    }
    public interface SbOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional string ssid = 1;</code>
       */
      String getSsid();
      /**
       * <code>optional string ssid = 1;</code>
       */
      com.google.protobuf.ByteString
          getSsidBytes();

      /**
       * <code>optional string bssid = 2;</code>
       */
      String getBssid();
      /**
       * <code>optional string bssid = 2;</code>
       */
      com.google.protobuf.ByteString
          getBssidBytes();

      /**
       * <code>optional sint32 securityLevel = 3;</code>
       */
      int getSecurityLevel();
    }
    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb}
     */
    public  static final class Sb extends
        com.google.protobuf.GeneratedMessageLite<
            Sb, Sb.Builder> implements
        // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb)
        SbOrBuilder {
      private Sb() {
        ssid_ = "";
        bssid_ = "";
      }
      public static final int SSID_FIELD_NUMBER = 1;
      private String ssid_;
      /**
       * <code>optional string ssid = 1;</code>
       */
      public String getSsid() {
        return ssid_;
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(ssid_);
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      private void setSsid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ssid_ = value;
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      private void clearSsid() {
        
        ssid_ = getDefaultInstance().getSsid();
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      private void setSsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ssid_ = value.toStringUtf8();
      }

      public static final int BSSID_FIELD_NUMBER = 2;
      private String bssid_;
      /**
       * <code>optional string bssid = 2;</code>
       */
      public String getBssid() {
        return bssid_;
      }
      /**
       * <code>optional string bssid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBssidBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(bssid_);
      }
      /**
       * <code>optional string bssid = 2;</code>
       */
      private void setBssid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bssid_ = value;
      }
      /**
       * <code>optional string bssid = 2;</code>
       */
      private void clearBssid() {
        
        bssid_ = getDefaultInstance().getBssid();
      }
      /**
       * <code>optional string bssid = 2;</code>
       */
      private void setBssidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bssid_ = value.toStringUtf8();
      }

      public static final int SECURITYLEVEL_FIELD_NUMBER = 3;
      private int securityLevel_;
      /**
       * <code>optional sint32 securityLevel = 3;</code>
       */
      public int getSecurityLevel() {
        return securityLevel_;
      }
      /**
       * <code>optional sint32 securityLevel = 3;</code>
       */
      private void setSecurityLevel(int value) {
        
        securityLevel_ = value;
      }
      /**
       * <code>optional sint32 securityLevel = 3;</code>
       */
      private void clearSecurityLevel() {
        
        securityLevel_ = 0;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!ssid_.isEmpty()) {
          output.writeString(1, getSsid());
        }
        if (!bssid_.isEmpty()) {
          output.writeString(2, getBssid());
        }
        if (securityLevel_ != 0) {
          output.writeSInt32(3, securityLevel_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!ssid_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getSsid());
        }
        if (!bssid_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getBssid());
        }
        if (securityLevel_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt32Size(3, securityLevel_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static Sb parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Sb parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Sb parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Sb parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Sb parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static Sb parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static Sb parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static Sb parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static Sb parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static Sb parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Sb prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            Sb, Builder> implements
          // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb)
          SbOrBuilder {
        // Construct using com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBeanOuterClass.ThirdApQueryListRequestBean.Sb.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional string ssid = 1;</code>
         */
        public String getSsid() {
          return instance.getSsid();
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public com.google.protobuf.ByteString
            getSsidBytes() {
          return instance.getSsidBytes();
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public Builder setSsid(
            String value) {
          copyOnWrite();
          instance.setSsid(value);
          return this;
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public Builder clearSsid() {
          copyOnWrite();
          instance.clearSsid();
          return this;
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public Builder setSsidBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setSsidBytes(value);
          return this;
        }

        /**
         * <code>optional string bssid = 2;</code>
         */
        public String getBssid() {
          return instance.getBssid();
        }
        /**
         * <code>optional string bssid = 2;</code>
         */
        public com.google.protobuf.ByteString
            getBssidBytes() {
          return instance.getBssidBytes();
        }
        /**
         * <code>optional string bssid = 2;</code>
         */
        public Builder setBssid(
            String value) {
          copyOnWrite();
          instance.setBssid(value);
          return this;
        }
        /**
         * <code>optional string bssid = 2;</code>
         */
        public Builder clearBssid() {
          copyOnWrite();
          instance.clearBssid();
          return this;
        }
        /**
         * <code>optional string bssid = 2;</code>
         */
        public Builder setBssidBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setBssidBytes(value);
          return this;
        }

        /**
         * <code>optional sint32 securityLevel = 3;</code>
         */
        public int getSecurityLevel() {
          return instance.getSecurityLevel();
        }
        /**
         * <code>optional sint32 securityLevel = 3;</code>
         */
        public Builder setSecurityLevel(int value) {
          copyOnWrite();
          instance.setSecurityLevel(value);
          return this;
        }
        /**
         * <code>optional sint32 securityLevel = 3;</code>
         */
        public Builder clearSecurityLevel() {
          copyOnWrite();
          instance.clearSecurityLevel();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb)
      }
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new Sb();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            Sb other = (Sb) arg1;
            ssid_ = visitor.visitString(!ssid_.isEmpty(), ssid_,
                !other.ssid_.isEmpty(), other.ssid_);
            bssid_ = visitor.visitString(!bssid_.isEmpty(), bssid_,
                !other.bssid_.isEmpty(), other.bssid_);
            securityLevel_ = visitor.visitInt(securityLevel_ != 0, securityLevel_,
                other.securityLevel_ != 0, other.securityLevel_);
            if (visitor == MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readStringRequireUtf8();

                    ssid_ = s;
                    break;
                  }
                  case 18: {
                    String s = input.readStringRequireUtf8();

                    bssid_ = s;
                    break;
                  }
                  case 24: {

                    securityLevel_ = input.readSInt32();
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (Sb.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb)
      private static final Sb DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Sb();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static Sb getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Sb> PARSER;

      public static com.google.protobuf.Parser<Sb> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int SB_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Sb> sb_;
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    public java.util.List<Sb> getSbList() {
      return sb_;
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    public java.util.List<? extends SbOrBuilder>
        getSbOrBuilderList() {
      return sb_;
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    public int getSbCount() {
      return sb_.size();
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    public Sb getSb(int index) {
      return sb_.get(index);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    public SbOrBuilder getSbOrBuilder(
        int index) {
      return sb_.get(index);
    }
    private void ensureSbIsMutable() {
      if (!sb_.isModifiable()) {
        sb_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(sb_);
       }
    }

    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void setSb(
        int index, Sb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSbIsMutable();
      sb_.set(index, value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void setSb(
        int index, Sb.Builder builderForValue) {
      ensureSbIsMutable();
      sb_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void addSb(Sb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSbIsMutable();
      sb_.add(value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void addSb(
        int index, Sb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSbIsMutable();
      sb_.add(index, value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void addSb(
        Sb.Builder builderForValue) {
      ensureSbIsMutable();
      sb_.add(builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void addSb(
        int index, Sb.Builder builderForValue) {
      ensureSbIsMutable();
      sb_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void addAllSb(
        Iterable<? extends Sb> values) {
      ensureSbIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, sb_);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void clearSb() {
      sb_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
     */
    private void removeSb(int index) {
      ensureSbIsMutable();
      sb_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sb_.size(); i++) {
        output.writeMessage(1, sb_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sb_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sb_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ThirdApQueryListRequestBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ThirdApQueryListRequestBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ThirdApQueryListRequestBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ThirdApQueryListRequestBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ThirdApQueryListRequestBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ThirdApQueryListRequestBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ThirdApQueryListRequestBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ThirdApQueryListRequestBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ThirdApQueryListRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ThirdApQueryListRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ThirdApQueryListRequestBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ThirdApQueryListRequestBean, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean)
        ThirdApQueryListRequestBeanOrBuilder {
      // Construct using com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBeanOuterClass.ThirdApQueryListRequestBean.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public java.util.List<Sb> getSbList() {
        return java.util.Collections.unmodifiableList(
            instance.getSbList());
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public int getSbCount() {
        return instance.getSbCount();
      }/**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Sb getSb(int index) {
        return instance.getSb(index);
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder setSb(
          int index, Sb value) {
        copyOnWrite();
        instance.setSb(index, value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder setSb(
          int index, Sb.Builder builderForValue) {
        copyOnWrite();
        instance.setSb(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder addSb(Sb value) {
        copyOnWrite();
        instance.addSb(value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder addSb(
          int index, Sb value) {
        copyOnWrite();
        instance.addSb(index, value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder addSb(
          Sb.Builder builderForValue) {
        copyOnWrite();
        instance.addSb(builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder addSb(
          int index, Sb.Builder builderForValue) {
        copyOnWrite();
        instance.addSb(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder addAllSb(
          Iterable<? extends Sb> values) {
        copyOnWrite();
        instance.addAllSb(values);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder clearSb() {
        copyOnWrite();
        instance.clearSb();
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean.Sb sb = 1;</code>
       */
      public Builder removeSb(int index) {
        copyOnWrite();
        instance.removeSb(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ThirdApQueryListRequestBean();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          sb_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ThirdApQueryListRequestBean other = (ThirdApQueryListRequestBean) arg1;
          sb_= visitor.visitList(sb_, other.sb_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!sb_.isModifiable()) {
                    sb_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(sb_);
                  }
                  sb_.add(
                      input.readMessage(Sb.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ThirdApQueryListRequestBean.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListRequestBean)
    private static final ThirdApQueryListRequestBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ThirdApQueryListRequestBean();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ThirdApQueryListRequestBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ThirdApQueryListRequestBean> PARSER;

    public static com.google.protobuf.Parser<ThirdApQueryListRequestBean> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
