// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThirdApQueryListResponseModel.proto

package com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf;

public final class ThirdApQueryListResponseModelOuterClass {
  private ThirdApQueryListResponseModelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ThirdApQueryListResponseModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string qid = 1;</code>
     */
    String getQid();
    /**
     * <code>optional string qid = 1;</code>
     */
    com.google.protobuf.ByteString
        getQidBytes();

    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */
    int getOapsCount();
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */
    boolean containsOaps(
            String key);
    /**
     * Use {@link #getOapsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, ThirdApQueryListResponseModel.MapField>
    getOaps();
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */
    java.util.Map<String, ThirdApQueryListResponseModel.MapField>
    getOapsMap();
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */

    ThirdApQueryListResponseModel.MapField getOapsOrDefault(
            String key,
            ThirdApQueryListResponseModel.MapField defaultValue);
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */

    ThirdApQueryListResponseModel.MapField getOapsOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel}
   */
  public  static final class ThirdApQueryListResponseModel extends
      com.google.protobuf.GeneratedMessageLite<
          ThirdApQueryListResponseModel, ThirdApQueryListResponseModel.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel)
      ThirdApQueryListResponseModelOrBuilder {
    private ThirdApQueryListResponseModel() {
      qid_ = "";
    }
    public interface MapFieldOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      int getMfCount();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      boolean containsMf(
              String key);
      /**
       * Use {@link #getMfMap()} instead.
       */
      @Deprecated
      java.util.Map<String, String>
      getMf();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      java.util.Map<String, String>
      getMfMap();
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      String getMfOrDefault(
              String key,
              String defaultValue);
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      String getMfOrThrow(
              String key);
    }
    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField}
     */
    public  static final class MapField extends
        com.google.protobuf.GeneratedMessageLite<
            MapField, MapField.Builder> implements
        // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField)
        MapFieldOrBuilder {
      private MapField() {
      }
      public static final int MF_FIELD_NUMBER = 1;
      private static final class MfDefaultEntryHolder {
        static final com.google.protobuf.MapEntryLite<
            String, String> defaultEntry =
                com.google.protobuf.MapEntryLite
                .<String, String>newDefaultInstance(
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "");
      }
      private com.google.protobuf.MapFieldLite<
          String, String> mf_ =
              com.google.protobuf.MapFieldLite.emptyMapField();
      private com.google.protobuf.MapFieldLite<String, String>
      internalGetMf() {
        return mf_;
      }
      private com.google.protobuf.MapFieldLite<String, String>
      internalGetMutableMf() {
        if (!mf_.isMutable()) {
          mf_ = mf_.mutableCopy();
        }
        return mf_;
      }

      public int getMfCount() {
        return internalGetMf().size();
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public boolean containsMf(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMf().containsKey(key);
      }
      /**
       * Use {@link #getMfMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getMf() {
        return getMfMap();
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public java.util.Map<String, String> getMfMap() {
        return java.util.Collections.unmodifiableMap(
            internalGetMf());
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public String getMfOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMf();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */

      public String getMfOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMf();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; mf = 1;</code>
       */
      private java.util.Map<String, String>
      getMutableMfMap() {
        return internalGetMutableMf();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (java.util.Map.Entry<String, String> entry
             : internalGetMf().entrySet()) {
          MfDefaultEntryHolder.defaultEntry.serializeTo(
              output, 1, entry.getKey(), entry.getValue());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<String, String> entry
             : internalGetMf().entrySet()) {
          size += MfDefaultEntryHolder.defaultEntry.computeMessageSize(
            1, entry.getKey(), entry.getValue());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static MapField parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static MapField parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static MapField parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static MapField parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static MapField parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static MapField parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static MapField parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static MapField parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static MapField parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static MapField parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MapField prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            MapField, Builder> implements
          // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField)
          MapFieldOrBuilder {
        // Construct using com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModelOuterClass.ThirdApQueryListResponseModel.MapField.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }



        public int getMfCount() {
          return instance.getMfMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public boolean containsMf(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          return instance.getMfMap().containsKey(key);
        }

        public Builder clearMf() {
          copyOnWrite();
          instance.getMutableMfMap().clear();
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public Builder removeMf(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          copyOnWrite();
          instance.getMutableMfMap().remove(key);
          return this;
        }
        /**
         * Use {@link #getMfMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, String> getMf() {
          return getMfMap();
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public java.util.Map<String, String> getMfMap() {
          return java.util.Collections.unmodifiableMap(
              instance.getMfMap());
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public String getMfOrDefault(
            String key,
            String defaultValue) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, String> map =
              instance.getMfMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */

        public String getMfOrThrow(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, String> map =
              instance.getMfMap();
          if (!map.containsKey(key)) {
            throw new IllegalArgumentException();
          }
          return map.get(key);
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public Builder putMf(
            String key,
            String value) {
          if (key == null) { throw new NullPointerException(); }
          if (value == null) { throw new NullPointerException(); }
          copyOnWrite();
          instance.getMutableMfMap().put(key, value);
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; mf = 1;</code>
         */
        public Builder putAllMf(
            java.util.Map<String, String> values) {
          copyOnWrite();
          instance.getMutableMfMap().putAll(values);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField)
      }
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new MapField();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            mf_.makeImmutable();
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            MapField other = (MapField) arg1;
            mf_ = visitor.visitMap(
                mf_, other.internalGetMf());
            if (visitor == MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    if (!mf_.isMutable()) {
                      mf_ = mf_.mutableCopy();
                    }
                    MfDefaultEntryHolder.defaultEntry.parseInto(mf_, input, extensionRegistry);  break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (MapField.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField)
      private static final MapField DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MapField();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static MapField getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<MapField> PARSER;

      public static com.google.protobuf.Parser<MapField> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int QID_FIELD_NUMBER = 1;
    private String qid_;
    /**
     * <code>optional string qid = 1;</code>
     */
    public String getQid() {
      return qid_;
    }
    /**
     * <code>optional string qid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(qid_);
    }
    /**
     * <code>optional string qid = 1;</code>
     */
    private void setQid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      qid_ = value;
    }
    /**
     * <code>optional string qid = 1;</code>
     */
    private void clearQid() {
      
      qid_ = getDefaultInstance().getQid();
    }
    /**
     * <code>optional string qid = 1;</code>
     */
    private void setQidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      qid_ = value.toStringUtf8();
    }

    public static final int OAPS_FIELD_NUMBER = 2;
    private static final class OapsDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          String, MapField> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<String, MapField>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  MapField.getDefaultInstance());
    }
    private com.google.protobuf.MapFieldLite<
        String, MapField> oaps_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<String, MapField>
    internalGetOaps() {
      return oaps_;
    }
    private com.google.protobuf.MapFieldLite<String, MapField>
    internalGetMutableOaps() {
      if (!oaps_.isMutable()) {
        oaps_ = oaps_.mutableCopy();
      }
      return oaps_;
    }

    public int getOapsCount() {
      return internalGetOaps().size();
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */

    public boolean containsOaps(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetOaps().containsKey(key);
    }
    /**
     * Use {@link #getOapsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, MapField> getOaps() {
      return getOapsMap();
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */

    public java.util.Map<String, MapField> getOapsMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetOaps());
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */

    public MapField getOapsOrDefault(
        String key,
        MapField defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, MapField> map =
          internalGetOaps();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */

    public MapField getOapsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, MapField> map =
          internalGetOaps();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
     */
    private java.util.Map<String, MapField>
    getMutableOapsMap() {
      return internalGetMutableOaps();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!qid_.isEmpty()) {
        output.writeString(1, getQid());
      }
      for (java.util.Map.Entry<String, MapField> entry
           : internalGetOaps().entrySet()) {
        OapsDefaultEntryHolder.defaultEntry.serializeTo(
            output, 2, entry.getKey(), entry.getValue());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!qid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getQid());
      }
      for (java.util.Map.Entry<String, MapField> entry
           : internalGetOaps().entrySet()) {
        size += OapsDefaultEntryHolder.defaultEntry.computeMessageSize(
          2, entry.getKey(), entry.getValue());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ThirdApQueryListResponseModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ThirdApQueryListResponseModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ThirdApQueryListResponseModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ThirdApQueryListResponseModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ThirdApQueryListResponseModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ThirdApQueryListResponseModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ThirdApQueryListResponseModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ThirdApQueryListResponseModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ThirdApQueryListResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ThirdApQueryListResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ThirdApQueryListResponseModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ThirdApQueryListResponseModel, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel)
        ThirdApQueryListResponseModelOrBuilder {
      // Construct using com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModelOuterClass.ThirdApQueryListResponseModel.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string qid = 1;</code>
       */
      public String getQid() {
        return instance.getQid();
      }
      /**
       * <code>optional string qid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQidBytes() {
        return instance.getQidBytes();
      }
      /**
       * <code>optional string qid = 1;</code>
       */
      public Builder setQid(
          String value) {
        copyOnWrite();
        instance.setQid(value);
        return this;
      }
      /**
       * <code>optional string qid = 1;</code>
       */
      public Builder clearQid() {
        copyOnWrite();
        instance.clearQid();
        return this;
      }
      /**
       * <code>optional string qid = 1;</code>
       */
      public Builder setQidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setQidBytes(value);
        return this;
      }


      public int getOapsCount() {
        return instance.getOapsMap().size();
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
       */

      public boolean containsOaps(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return instance.getOapsMap().containsKey(key);
      }

      public Builder clearOaps() {
        copyOnWrite();
        instance.getMutableOapsMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
       */

      public Builder removeOaps(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        copyOnWrite();
        instance.getMutableOapsMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getOapsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, MapField> getOaps() {
        return getOapsMap();
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
       */
      public java.util.Map<String, MapField> getOapsMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getOapsMap());
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
       */

      public MapField getOapsOrDefault(
          String key,
          MapField defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, MapField> map =
            instance.getOapsMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
       */

      public MapField getOapsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, MapField> map =
            instance.getOapsMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
       */
      public Builder putOaps(
          String key,
          MapField value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        copyOnWrite();
        instance.getMutableOapsMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel.MapField&gt; oaps = 2;</code>
       */
      public Builder putAllOaps(
          java.util.Map<String, MapField> values) {
        copyOnWrite();
        instance.getMutableOapsMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ThirdApQueryListResponseModel();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          oaps_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ThirdApQueryListResponseModel other = (ThirdApQueryListResponseModel) arg1;
          qid_ = visitor.visitString(!qid_.isEmpty(), qid_,
              !other.qid_.isEmpty(), other.qid_);
          oaps_ = visitor.visitMap(
              oaps_, other.internalGetOaps());
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  qid_ = s;
                  break;
                }
                case 18: {
                  if (!oaps_.isMutable()) {
                    oaps_ = oaps_.mutableCopy();
                  }
                  OapsDefaultEntryHolder.defaultEntry.parseInto(oaps_, input, extensionRegistry);  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ThirdApQueryListResponseModel.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.open.thirdap.protobuf.ThirdApQueryListResponseModel)
    private static final ThirdApQueryListResponseModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ThirdApQueryListResponseModel();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ThirdApQueryListResponseModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ThirdApQueryListResponseModel> PARSER;

    public static com.google.protobuf.Parser<ThirdApQueryListResponseModel> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
