// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApCancelRequestBean.proto

package com.halo.ap.web.cmd.apcancel.protobuf;

public final class ApCancelRequestBeanOuterClass {
  private ApCancelRequestBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApCancelRequestBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.apcancel.protobuf.ApCancelRequestBean)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string bssid = 1;</code>
     */
    String getBssid();
    /**
     * <code>optional string bssid = 1;</code>
     */
    com.google.protobuf.ByteString
        getBssidBytes();

    /**
     * <code>optional string ssid = 2;</code>
     */
    String getSsid();
    /**
     * <code>optional string ssid = 2;</code>
     */
    com.google.protobuf.ByteString
        getSsidBytes();

    /**
     * <code>optional string pwd = 3;</code>
     */
    String getPwd();
    /**
     * <code>optional string pwd = 3;</code>
     */
    com.google.protobuf.ByteString
        getPwdBytes();

    /**
     * <code>optional string url = 4;</code>
     */
    String getUrl();
    /**
     * <code>optional string url = 4;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional string contactInfo = 5;</code>
     */
    String getContactInfo();
    /**
     * <code>optional string contactInfo = 5;</code>
     */
    com.google.protobuf.ByteString
        getContactInfoBytes();
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.apcancel.protobuf.ApCancelRequestBean}
   */
  public  static final class ApCancelRequestBean extends
      com.google.protobuf.GeneratedMessageLite<
          ApCancelRequestBean, ApCancelRequestBean.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.apcancel.protobuf.ApCancelRequestBean)
      ApCancelRequestBeanOrBuilder {
    private ApCancelRequestBean() {
      bssid_ = "";
      ssid_ = "";
      pwd_ = "";
      url_ = "";
      contactInfo_ = "";
    }
    public static final int BSSID_FIELD_NUMBER = 1;
    private String bssid_;
    /**
     * <code>optional string bssid = 1;</code>
     */
    public String getBssid() {
      return bssid_;
    }
    /**
     * <code>optional string bssid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBssidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(bssid_);
    }
    /**
     * <code>optional string bssid = 1;</code>
     */
    private void setBssid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bssid_ = value;
    }
    /**
     * <code>optional string bssid = 1;</code>
     */
    private void clearBssid() {
      
      bssid_ = getDefaultInstance().getBssid();
    }
    /**
     * <code>optional string bssid = 1;</code>
     */
    private void setBssidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bssid_ = value.toStringUtf8();
    }

    public static final int SSID_FIELD_NUMBER = 2;
    private String ssid_;
    /**
     * <code>optional string ssid = 2;</code>
     */
    public String getSsid() {
      return ssid_;
    }
    /**
     * <code>optional string ssid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSsidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ssid_);
    }
    /**
     * <code>optional string ssid = 2;</code>
     */
    private void setSsid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ssid_ = value;
    }
    /**
     * <code>optional string ssid = 2;</code>
     */
    private void clearSsid() {
      
      ssid_ = getDefaultInstance().getSsid();
    }
    /**
     * <code>optional string ssid = 2;</code>
     */
    private void setSsidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ssid_ = value.toStringUtf8();
    }

    public static final int PWD_FIELD_NUMBER = 3;
    private String pwd_;
    /**
     * <code>optional string pwd = 3;</code>
     */
    public String getPwd() {
      return pwd_;
    }
    /**
     * <code>optional string pwd = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPwdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pwd_);
    }
    /**
     * <code>optional string pwd = 3;</code>
     */
    private void setPwd(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pwd_ = value;
    }
    /**
     * <code>optional string pwd = 3;</code>
     */
    private void clearPwd() {
      
      pwd_ = getDefaultInstance().getPwd();
    }
    /**
     * <code>optional string pwd = 3;</code>
     */
    private void setPwdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pwd_ = value.toStringUtf8();
    }

    public static final int URL_FIELD_NUMBER = 4;
    private String url_;
    /**
     * <code>optional string url = 4;</code>
     */
    public String getUrl() {
      return url_;
    }
    /**
     * <code>optional string url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(url_);
    }
    /**
     * <code>optional string url = 4;</code>
     */
    private void setUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
    }
    /**
     * <code>optional string url = 4;</code>
     */
    private void clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
    }
    /**
     * <code>optional string url = 4;</code>
     */
    private void setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value.toStringUtf8();
    }

    public static final int CONTACTINFO_FIELD_NUMBER = 5;
    private String contactInfo_;
    /**
     * <code>optional string contactInfo = 5;</code>
     */
    public String getContactInfo() {
      return contactInfo_;
    }
    /**
     * <code>optional string contactInfo = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContactInfoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(contactInfo_);
    }
    /**
     * <code>optional string contactInfo = 5;</code>
     */
    private void setContactInfo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contactInfo_ = value;
    }
    /**
     * <code>optional string contactInfo = 5;</code>
     */
    private void clearContactInfo() {
      
      contactInfo_ = getDefaultInstance().getContactInfo();
    }
    /**
     * <code>optional string contactInfo = 5;</code>
     */
    private void setContactInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contactInfo_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!bssid_.isEmpty()) {
        output.writeString(1, getBssid());
      }
      if (!ssid_.isEmpty()) {
        output.writeString(2, getSsid());
      }
      if (!pwd_.isEmpty()) {
        output.writeString(3, getPwd());
      }
      if (!url_.isEmpty()) {
        output.writeString(4, getUrl());
      }
      if (!contactInfo_.isEmpty()) {
        output.writeString(5, getContactInfo());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!bssid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getBssid());
      }
      if (!ssid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getSsid());
      }
      if (!pwd_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPwd());
      }
      if (!url_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getUrl());
      }
      if (!contactInfo_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getContactInfo());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApCancelRequestBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApCancelRequestBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApCancelRequestBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApCancelRequestBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApCancelRequestBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApCancelRequestBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApCancelRequestBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApCancelRequestBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApCancelRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApCancelRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApCancelRequestBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.apcancel.protobuf.ApCancelRequestBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApCancelRequestBean, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.apcancel.protobuf.ApCancelRequestBean)
        ApCancelRequestBeanOrBuilder {
      // Construct using com.halo.ap.web.cmd.apcancel.protobuf.ApCancelRequestBeanOuterClass.ApCancelRequestBean.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string bssid = 1;</code>
       */
      public String getBssid() {
        return instance.getBssid();
      }
      /**
       * <code>optional string bssid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBssidBytes() {
        return instance.getBssidBytes();
      }
      /**
       * <code>optional string bssid = 1;</code>
       */
      public Builder setBssid(
          String value) {
        copyOnWrite();
        instance.setBssid(value);
        return this;
      }
      /**
       * <code>optional string bssid = 1;</code>
       */
      public Builder clearBssid() {
        copyOnWrite();
        instance.clearBssid();
        return this;
      }
      /**
       * <code>optional string bssid = 1;</code>
       */
      public Builder setBssidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBssidBytes(value);
        return this;
      }

      /**
       * <code>optional string ssid = 2;</code>
       */
      public String getSsid() {
        return instance.getSsid();
      }
      /**
       * <code>optional string ssid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        return instance.getSsidBytes();
      }
      /**
       * <code>optional string ssid = 2;</code>
       */
      public Builder setSsid(
          String value) {
        copyOnWrite();
        instance.setSsid(value);
        return this;
      }
      /**
       * <code>optional string ssid = 2;</code>
       */
      public Builder clearSsid() {
        copyOnWrite();
        instance.clearSsid();
        return this;
      }
      /**
       * <code>optional string ssid = 2;</code>
       */
      public Builder setSsidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSsidBytes(value);
        return this;
      }

      /**
       * <code>optional string pwd = 3;</code>
       */
      public String getPwd() {
        return instance.getPwd();
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPwdBytes() {
        return instance.getPwdBytes();
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public Builder setPwd(
          String value) {
        copyOnWrite();
        instance.setPwd(value);
        return this;
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public Builder clearPwd() {
        copyOnWrite();
        instance.clearPwd();
        return this;
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public Builder setPwdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPwdBytes(value);
        return this;
      }

      /**
       * <code>optional string url = 4;</code>
       */
      public String getUrl() {
        return instance.getUrl();
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        return instance.getUrlBytes();
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public Builder setUrl(
          String value) {
        copyOnWrite();
        instance.setUrl(value);
        return this;
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public Builder clearUrl() {
        copyOnWrite();
        instance.clearUrl();
        return this;
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUrlBytes(value);
        return this;
      }

      /**
       * <code>optional string contactInfo = 5;</code>
       */
      public String getContactInfo() {
        return instance.getContactInfo();
      }
      /**
       * <code>optional string contactInfo = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContactInfoBytes() {
        return instance.getContactInfoBytes();
      }
      /**
       * <code>optional string contactInfo = 5;</code>
       */
      public Builder setContactInfo(
          String value) {
        copyOnWrite();
        instance.setContactInfo(value);
        return this;
      }
      /**
       * <code>optional string contactInfo = 5;</code>
       */
      public Builder clearContactInfo() {
        copyOnWrite();
        instance.clearContactInfo();
        return this;
      }
      /**
       * <code>optional string contactInfo = 5;</code>
       */
      public Builder setContactInfoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContactInfoBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.apcancel.protobuf.ApCancelRequestBean)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApCancelRequestBean();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApCancelRequestBean other = (ApCancelRequestBean) arg1;
          bssid_ = visitor.visitString(!bssid_.isEmpty(), bssid_,
              !other.bssid_.isEmpty(), other.bssid_);
          ssid_ = visitor.visitString(!ssid_.isEmpty(), ssid_,
              !other.ssid_.isEmpty(), other.ssid_);
          pwd_ = visitor.visitString(!pwd_.isEmpty(), pwd_,
              !other.pwd_.isEmpty(), other.pwd_);
          url_ = visitor.visitString(!url_.isEmpty(), url_,
              !other.url_.isEmpty(), other.url_);
          contactInfo_ = visitor.visitString(!contactInfo_.isEmpty(), contactInfo_,
              !other.contactInfo_.isEmpty(), other.contactInfo_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  bssid_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  ssid_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  pwd_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  url_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  contactInfo_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApCancelRequestBean.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.apcancel.protobuf.ApCancelRequestBean)
    private static final ApCancelRequestBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApCancelRequestBean();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApCancelRequestBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApCancelRequestBean> PARSER;

    public static com.google.protobuf.Parser<ApCancelRequestBean> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
