// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApQueryListRequestBean.proto

package com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf;

public final class ApQueryListRequestBeanOuterClass {
  private ApQueryListRequestBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApQueryListRequestBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf.ApQueryListRequestBean)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string sn = 1;</code>
     */
    String getSn();
    /**
     * <code>optional string sn = 1;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    /**
     * <code>optional string lac = 2;</code>
     */
    String getLac();
    /**
     * <code>optional string lac = 2;</code>
     */
    com.google.protobuf.ByteString
        getLacBytes();

    /**
     * <code>optional string cid = 3;</code>
     */
    String getCid();
    /**
     * <code>optional string cid = 3;</code>
     */
    com.google.protobuf.ByteString
        getCidBytes();

    /**
     * <code>optional string sb = 4;</code>
     */
    String getSb();
    /**
     * <code>optional string sb = 4;</code>
     */
    com.google.protobuf.ByteString
        getSbBytes();
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf.ApQueryListRequestBean}
   */
  public  static final class ApQueryListRequestBean extends
      com.google.protobuf.GeneratedMessageLite<
          ApQueryListRequestBean, ApQueryListRequestBean.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf.ApQueryListRequestBean)
      ApQueryListRequestBeanOrBuilder {
    private ApQueryListRequestBean() {
      sn_ = "";
      lac_ = "";
      cid_ = "";
      sb_ = "";
    }
    public static final int SN_FIELD_NUMBER = 1;
    private String sn_;
    /**
     * <code>optional string sn = 1;</code>
     */
    public String getSn() {
      return sn_;
    }
    /**
     * <code>optional string sn = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sn_);
    }
    /**
     * <code>optional string sn = 1;</code>
     */
    private void setSn(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sn_ = value;
    }
    /**
     * <code>optional string sn = 1;</code>
     */
    private void clearSn() {
      
      sn_ = getDefaultInstance().getSn();
    }
    /**
     * <code>optional string sn = 1;</code>
     */
    private void setSnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sn_ = value.toStringUtf8();
    }

    public static final int LAC_FIELD_NUMBER = 2;
    private String lac_;
    /**
     * <code>optional string lac = 2;</code>
     */
    public String getLac() {
      return lac_;
    }
    /**
     * <code>optional string lac = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLacBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lac_);
    }
    /**
     * <code>optional string lac = 2;</code>
     */
    private void setLac(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lac_ = value;
    }
    /**
     * <code>optional string lac = 2;</code>
     */
    private void clearLac() {
      
      lac_ = getDefaultInstance().getLac();
    }
    /**
     * <code>optional string lac = 2;</code>
     */
    private void setLacBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lac_ = value.toStringUtf8();
    }

    public static final int CID_FIELD_NUMBER = 3;
    private String cid_;
    /**
     * <code>optional string cid = 3;</code>
     */
    public String getCid() {
      return cid_;
    }
    /**
     * <code>optional string cid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cid_);
    }
    /**
     * <code>optional string cid = 3;</code>
     */
    private void setCid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cid_ = value;
    }
    /**
     * <code>optional string cid = 3;</code>
     */
    private void clearCid() {
      
      cid_ = getDefaultInstance().getCid();
    }
    /**
     * <code>optional string cid = 3;</code>
     */
    private void setCidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cid_ = value.toStringUtf8();
    }

    public static final int SB_FIELD_NUMBER = 4;
    private String sb_;
    /**
     * <code>optional string sb = 4;</code>
     */
    public String getSb() {
      return sb_;
    }
    /**
     * <code>optional string sb = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSbBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sb_);
    }
    /**
     * <code>optional string sb = 4;</code>
     */
    private void setSb(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sb_ = value;
    }
    /**
     * <code>optional string sb = 4;</code>
     */
    private void clearSb() {
      
      sb_ = getDefaultInstance().getSb();
    }
    /**
     * <code>optional string sb = 4;</code>
     */
    private void setSbBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sb_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!sn_.isEmpty()) {
        output.writeString(1, getSn());
      }
      if (!lac_.isEmpty()) {
        output.writeString(2, getLac());
      }
      if (!cid_.isEmpty()) {
        output.writeString(3, getCid());
      }
      if (!sb_.isEmpty()) {
        output.writeString(4, getSb());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!sn_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSn());
      }
      if (!lac_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getLac());
      }
      if (!cid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getCid());
      }
      if (!sb_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSb());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApQueryListRequestBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApQueryListRequestBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApQueryListRequestBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApQueryListRequestBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApQueryListRequestBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApQueryListRequestBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApQueryListRequestBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApQueryListRequestBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApQueryListRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApQueryListRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApQueryListRequestBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf.ApQueryListRequestBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApQueryListRequestBean, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf.ApQueryListRequestBean)
        ApQueryListRequestBeanOrBuilder {
      // Construct using com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf.ApQueryListRequestBeanOuterClass.ApQueryListRequestBean.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string sn = 1;</code>
       */
      public String getSn() {
        return instance.getSn();
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        return instance.getSnBytes();
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public Builder setSn(
          String value) {
        copyOnWrite();
        instance.setSn(value);
        return this;
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public Builder clearSn() {
        copyOnWrite();
        instance.clearSn();
        return this;
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSnBytes(value);
        return this;
      }

      /**
       * <code>optional string lac = 2;</code>
       */
      public String getLac() {
        return instance.getLac();
      }
      /**
       * <code>optional string lac = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLacBytes() {
        return instance.getLacBytes();
      }
      /**
       * <code>optional string lac = 2;</code>
       */
      public Builder setLac(
          String value) {
        copyOnWrite();
        instance.setLac(value);
        return this;
      }
      /**
       * <code>optional string lac = 2;</code>
       */
      public Builder clearLac() {
        copyOnWrite();
        instance.clearLac();
        return this;
      }
      /**
       * <code>optional string lac = 2;</code>
       */
      public Builder setLacBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLacBytes(value);
        return this;
      }

      /**
       * <code>optional string cid = 3;</code>
       */
      public String getCid() {
        return instance.getCid();
      }
      /**
       * <code>optional string cid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCidBytes() {
        return instance.getCidBytes();
      }
      /**
       * <code>optional string cid = 3;</code>
       */
      public Builder setCid(
          String value) {
        copyOnWrite();
        instance.setCid(value);
        return this;
      }
      /**
       * <code>optional string cid = 3;</code>
       */
      public Builder clearCid() {
        copyOnWrite();
        instance.clearCid();
        return this;
      }
      /**
       * <code>optional string cid = 3;</code>
       */
      public Builder setCidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCidBytes(value);
        return this;
      }

      /**
       * <code>optional string sb = 4;</code>
       */
      public String getSb() {
        return instance.getSb();
      }
      /**
       * <code>optional string sb = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSbBytes() {
        return instance.getSbBytes();
      }
      /**
       * <code>optional string sb = 4;</code>
       */
      public Builder setSb(
          String value) {
        copyOnWrite();
        instance.setSb(value);
        return this;
      }
      /**
       * <code>optional string sb = 4;</code>
       */
      public Builder clearSb() {
        copyOnWrite();
        instance.clearSb();
        return this;
      }
      /**
       * <code>optional string sb = 4;</code>
       */
      public Builder setSbBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSbBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf.ApQueryListRequestBean)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApQueryListRequestBean();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApQueryListRequestBean other = (ApQueryListRequestBean) arg1;
          sn_ = visitor.visitString(!sn_.isEmpty(), sn_,
              !other.sn_.isEmpty(), other.sn_);
          lac_ = visitor.visitString(!lac_.isEmpty(), lac_,
              !other.lac_.isEmpty(), other.lac_);
          cid_ = visitor.visitString(!cid_.isEmpty(), cid_,
              !other.cid_.isEmpty(), other.cid_);
          sb_ = visitor.visitString(!sb_.isEmpty(), sb_,
              !other.sb_.isEmpty(), other.sb_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  sn_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  lac_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  cid_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  sb_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApQueryListRequestBean.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.qryap.askpwds.v3.protobuf.ApQueryListRequestBean)
    private static final ApQueryListRequestBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApQueryListRequestBean();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApQueryListRequestBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApQueryListRequestBean> PARSER;

    public static com.google.protobuf.Parser<ApQueryListRequestBean> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
