/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_JniUtil */

#ifndef _Included_com_example_ndk_JniUtil
#define _Included_com_example_ndk_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_JniUtil
 * Method:    getJniStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_JniUtil_getJniStr
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_JniUtil
 * Method:    crash
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_JniUtil_crash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
