// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApShareRequestBean.proto

package com.halo.ap.web.cmd.shareap.v3.protobuf;

public final class ApShareRequestBeanOuterClass {
  private ApShareRequestBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApShareRequestBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    java.util.List<ApShareRequestBean.Nbaps>
        getNbapsList();
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    ApShareRequestBean.Nbaps getNbaps(int index);
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    int getNbapsCount();

    /**
     * <code>optional string pwd = 2;</code>
     */
    String getPwd();
    /**
     * <code>optional string pwd = 2;</code>
     */
    com.google.protobuf.ByteString
        getPwdBytes();

    /**
     * <code>optional sint32 shareType = 3;</code>
     */
    int getShareType();

    /**
     * <code>optional sint32 securityLevel = 4;</code>
     */
    int getSecurityLevel();

    /**
     * <code>optional sint32 authType = 5;</code>
     */
    int getAuthType();

    /**
     * <code>optional string bssid = 6;</code>
     */
    String getBssid();
    /**
     * <code>optional string bssid = 6;</code>
     */
    com.google.protobuf.ByteString
        getBssidBytes();

    /**
     * <code>optional string ssid = 7;</code>
     */
    String getSsid();
    /**
     * <code>optional string ssid = 7;</code>
     */
    com.google.protobuf.ByteString
        getSsidBytes();

    /**
     * <code>optional string sn = 8;</code>
     */
    String getSn();
    /**
     * <code>optional string sn = 8;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    /**
     * <code>optional string lac = 9;</code>
     */
    String getLac();
    /**
     * <code>optional string lac = 9;</code>
     */
    com.google.protobuf.ByteString
        getLacBytes();

    /**
     * <code>optional string cid = 10;</code>
     */
    String getCid();
    /**
     * <code>optional string cid = 10;</code>
     */
    com.google.protobuf.ByteString
        getCidBytes();
  }
  /**
   * Protobuf type {@code com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean}
   */
  public  static final class ApShareRequestBean extends
      com.google.protobuf.GeneratedMessageLite<
          ApShareRequestBean, ApShareRequestBean.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean)
      ApShareRequestBeanOrBuilder {
    private ApShareRequestBean() {
      nbaps_ = emptyProtobufList();
      pwd_ = "";
      bssid_ = "";
      ssid_ = "";
      sn_ = "";
      lac_ = "";
      cid_ = "";
    }
    public interface NbapsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional string ssid = 1;</code>
       */
      String getSsid();
      /**
       * <code>optional string ssid = 1;</code>
       */
      com.google.protobuf.ByteString
          getSsidBytes();

      /**
       * <code>optional string bssid = 2;</code>
       */
      String getBssid();
      /**
       * <code>optional string bssid = 2;</code>
       */
      com.google.protobuf.ByteString
          getBssidBytes();

      /**
       * <code>optional string rssi = 3;</code>
       */
      String getRssi();
      /**
       * <code>optional string rssi = 3;</code>
       */
      com.google.protobuf.ByteString
          getRssiBytes();

      /**
       * <code>optional sint32 securityLevel = 4;</code>
       */
      int getSecurityLevel();
    }
    /**
     * Protobuf type {@code com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps}
     */
    public  static final class Nbaps extends
        com.google.protobuf.GeneratedMessageLite<
            Nbaps, Nbaps.Builder> implements
        // @@protoc_insertion_point(message_implements:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps)
        NbapsOrBuilder {
      private Nbaps() {
        ssid_ = "";
        bssid_ = "";
        rssi_ = "";
      }
      public static final int SSID_FIELD_NUMBER = 1;
      private String ssid_;
      /**
       * <code>optional string ssid = 1;</code>
       */
      public String getSsid() {
        return ssid_;
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(ssid_);
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      private void setSsid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ssid_ = value;
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      private void clearSsid() {
        
        ssid_ = getDefaultInstance().getSsid();
      }
      /**
       * <code>optional string ssid = 1;</code>
       */
      private void setSsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ssid_ = value.toStringUtf8();
      }

      public static final int BSSID_FIELD_NUMBER = 2;
      private String bssid_;
      /**
       * <code>optional string bssid = 2;</code>
       */
      public String getBssid() {
        return bssid_;
      }
      /**
       * <code>optional string bssid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBssidBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(bssid_);
      }
      /**
       * <code>optional string bssid = 2;</code>
       */
      private void setBssid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bssid_ = value;
      }
      /**
       * <code>optional string bssid = 2;</code>
       */
      private void clearBssid() {
        
        bssid_ = getDefaultInstance().getBssid();
      }
      /**
       * <code>optional string bssid = 2;</code>
       */
      private void setBssidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bssid_ = value.toStringUtf8();
      }

      public static final int RSSI_FIELD_NUMBER = 3;
      private String rssi_;
      /**
       * <code>optional string rssi = 3;</code>
       */
      public String getRssi() {
        return rssi_;
      }
      /**
       * <code>optional string rssi = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRssiBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(rssi_);
      }
      /**
       * <code>optional string rssi = 3;</code>
       */
      private void setRssi(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rssi_ = value;
      }
      /**
       * <code>optional string rssi = 3;</code>
       */
      private void clearRssi() {
        
        rssi_ = getDefaultInstance().getRssi();
      }
      /**
       * <code>optional string rssi = 3;</code>
       */
      private void setRssiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rssi_ = value.toStringUtf8();
      }

      public static final int SECURITYLEVEL_FIELD_NUMBER = 4;
      private int securityLevel_;
      /**
       * <code>optional sint32 securityLevel = 4;</code>
       */
      public int getSecurityLevel() {
        return securityLevel_;
      }
      /**
       * <code>optional sint32 securityLevel = 4;</code>
       */
      private void setSecurityLevel(int value) {
        
        securityLevel_ = value;
      }
      /**
       * <code>optional sint32 securityLevel = 4;</code>
       */
      private void clearSecurityLevel() {
        
        securityLevel_ = 0;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!ssid_.isEmpty()) {
          output.writeString(1, getSsid());
        }
        if (!bssid_.isEmpty()) {
          output.writeString(2, getBssid());
        }
        if (!rssi_.isEmpty()) {
          output.writeString(3, getRssi());
        }
        if (securityLevel_ != 0) {
          output.writeSInt32(4, securityLevel_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!ssid_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getSsid());
        }
        if (!bssid_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getBssid());
        }
        if (!rssi_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(3, getRssi());
        }
        if (securityLevel_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt32Size(4, securityLevel_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static Nbaps parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Nbaps parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Nbaps parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Nbaps parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Nbaps parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static Nbaps parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static Nbaps parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static Nbaps parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static Nbaps parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static Nbaps parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Nbaps prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            Nbaps, Builder> implements
          // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps)
          NbapsOrBuilder {
        // Construct using com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBeanOuterClass.ApShareRequestBean.Nbaps.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional string ssid = 1;</code>
         */
        public String getSsid() {
          return instance.getSsid();
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public com.google.protobuf.ByteString
            getSsidBytes() {
          return instance.getSsidBytes();
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public Builder setSsid(
            String value) {
          copyOnWrite();
          instance.setSsid(value);
          return this;
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public Builder clearSsid() {
          copyOnWrite();
          instance.clearSsid();
          return this;
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public Builder setSsidBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setSsidBytes(value);
          return this;
        }

        /**
         * <code>optional string bssid = 2;</code>
         */
        public String getBssid() {
          return instance.getBssid();
        }
        /**
         * <code>optional string bssid = 2;</code>
         */
        public com.google.protobuf.ByteString
            getBssidBytes() {
          return instance.getBssidBytes();
        }
        /**
         * <code>optional string bssid = 2;</code>
         */
        public Builder setBssid(
            String value) {
          copyOnWrite();
          instance.setBssid(value);
          return this;
        }
        /**
         * <code>optional string bssid = 2;</code>
         */
        public Builder clearBssid() {
          copyOnWrite();
          instance.clearBssid();
          return this;
        }
        /**
         * <code>optional string bssid = 2;</code>
         */
        public Builder setBssidBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setBssidBytes(value);
          return this;
        }

        /**
         * <code>optional string rssi = 3;</code>
         */
        public String getRssi() {
          return instance.getRssi();
        }
        /**
         * <code>optional string rssi = 3;</code>
         */
        public com.google.protobuf.ByteString
            getRssiBytes() {
          return instance.getRssiBytes();
        }
        /**
         * <code>optional string rssi = 3;</code>
         */
        public Builder setRssi(
            String value) {
          copyOnWrite();
          instance.setRssi(value);
          return this;
        }
        /**
         * <code>optional string rssi = 3;</code>
         */
        public Builder clearRssi() {
          copyOnWrite();
          instance.clearRssi();
          return this;
        }
        /**
         * <code>optional string rssi = 3;</code>
         */
        public Builder setRssiBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setRssiBytes(value);
          return this;
        }

        /**
         * <code>optional sint32 securityLevel = 4;</code>
         */
        public int getSecurityLevel() {
          return instance.getSecurityLevel();
        }
        /**
         * <code>optional sint32 securityLevel = 4;</code>
         */
        public Builder setSecurityLevel(int value) {
          copyOnWrite();
          instance.setSecurityLevel(value);
          return this;
        }
        /**
         * <code>optional sint32 securityLevel = 4;</code>
         */
        public Builder clearSecurityLevel() {
          copyOnWrite();
          instance.clearSecurityLevel();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps)
      }
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new Nbaps();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            Nbaps other = (Nbaps) arg1;
            ssid_ = visitor.visitString(!ssid_.isEmpty(), ssid_,
                !other.ssid_.isEmpty(), other.ssid_);
            bssid_ = visitor.visitString(!bssid_.isEmpty(), bssid_,
                !other.bssid_.isEmpty(), other.bssid_);
            rssi_ = visitor.visitString(!rssi_.isEmpty(), rssi_,
                !other.rssi_.isEmpty(), other.rssi_);
            securityLevel_ = visitor.visitInt(securityLevel_ != 0, securityLevel_,
                other.securityLevel_ != 0, other.securityLevel_);
            if (visitor == MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readStringRequireUtf8();

                    ssid_ = s;
                    break;
                  }
                  case 18: {
                    String s = input.readStringRequireUtf8();

                    bssid_ = s;
                    break;
                  }
                  case 26: {
                    String s = input.readStringRequireUtf8();

                    rssi_ = s;
                    break;
                  }
                  case 32: {

                    securityLevel_ = input.readSInt32();
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (Nbaps.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps)
      private static final Nbaps DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Nbaps();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static Nbaps getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Nbaps> PARSER;

      public static com.google.protobuf.Parser<Nbaps> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int NBAPS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Nbaps> nbaps_;
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    public java.util.List<Nbaps> getNbapsList() {
      return nbaps_;
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    public java.util.List<? extends NbapsOrBuilder>
        getNbapsOrBuilderList() {
      return nbaps_;
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    public int getNbapsCount() {
      return nbaps_.size();
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    public Nbaps getNbaps(int index) {
      return nbaps_.get(index);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    public NbapsOrBuilder getNbapsOrBuilder(
        int index) {
      return nbaps_.get(index);
    }
    private void ensureNbapsIsMutable() {
      if (!nbaps_.isModifiable()) {
        nbaps_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(nbaps_);
       }
    }

    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void setNbaps(
        int index, Nbaps value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNbapsIsMutable();
      nbaps_.set(index, value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void setNbaps(
        int index, Nbaps.Builder builderForValue) {
      ensureNbapsIsMutable();
      nbaps_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void addNbaps(Nbaps value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNbapsIsMutable();
      nbaps_.add(value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void addNbaps(
        int index, Nbaps value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNbapsIsMutable();
      nbaps_.add(index, value);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void addNbaps(
        Nbaps.Builder builderForValue) {
      ensureNbapsIsMutable();
      nbaps_.add(builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void addNbaps(
        int index, Nbaps.Builder builderForValue) {
      ensureNbapsIsMutable();
      nbaps_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void addAllNbaps(
        Iterable<? extends Nbaps> values) {
      ensureNbapsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, nbaps_);
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void clearNbaps() {
      nbaps_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
     */
    private void removeNbaps(int index) {
      ensureNbapsIsMutable();
      nbaps_.remove(index);
    }

    public static final int PWD_FIELD_NUMBER = 2;
    private String pwd_;
    /**
     * <code>optional string pwd = 2;</code>
     */
    public String getPwd() {
      return pwd_;
    }
    /**
     * <code>optional string pwd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPwdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pwd_);
    }
    /**
     * <code>optional string pwd = 2;</code>
     */
    private void setPwd(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pwd_ = value;
    }
    /**
     * <code>optional string pwd = 2;</code>
     */
    private void clearPwd() {
      
      pwd_ = getDefaultInstance().getPwd();
    }
    /**
     * <code>optional string pwd = 2;</code>
     */
    private void setPwdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pwd_ = value.toStringUtf8();
    }

    public static final int SHARETYPE_FIELD_NUMBER = 3;
    private int shareType_;
    /**
     * <code>optional sint32 shareType = 3;</code>
     */
    public int getShareType() {
      return shareType_;
    }
    /**
     * <code>optional sint32 shareType = 3;</code>
     */
    private void setShareType(int value) {
      
      shareType_ = value;
    }
    /**
     * <code>optional sint32 shareType = 3;</code>
     */
    private void clearShareType() {
      
      shareType_ = 0;
    }

    public static final int SECURITYLEVEL_FIELD_NUMBER = 4;
    private int securityLevel_;
    /**
     * <code>optional sint32 securityLevel = 4;</code>
     */
    public int getSecurityLevel() {
      return securityLevel_;
    }
    /**
     * <code>optional sint32 securityLevel = 4;</code>
     */
    private void setSecurityLevel(int value) {
      
      securityLevel_ = value;
    }
    /**
     * <code>optional sint32 securityLevel = 4;</code>
     */
    private void clearSecurityLevel() {
      
      securityLevel_ = 0;
    }

    public static final int AUTHTYPE_FIELD_NUMBER = 5;
    private int authType_;
    /**
     * <code>optional sint32 authType = 5;</code>
     */
    public int getAuthType() {
      return authType_;
    }
    /**
     * <code>optional sint32 authType = 5;</code>
     */
    private void setAuthType(int value) {
      
      authType_ = value;
    }
    /**
     * <code>optional sint32 authType = 5;</code>
     */
    private void clearAuthType() {
      
      authType_ = 0;
    }

    public static final int BSSID_FIELD_NUMBER = 6;
    private String bssid_;
    /**
     * <code>optional string bssid = 6;</code>
     */
    public String getBssid() {
      return bssid_;
    }
    /**
     * <code>optional string bssid = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBssidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(bssid_);
    }
    /**
     * <code>optional string bssid = 6;</code>
     */
    private void setBssid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bssid_ = value;
    }
    /**
     * <code>optional string bssid = 6;</code>
     */
    private void clearBssid() {
      
      bssid_ = getDefaultInstance().getBssid();
    }
    /**
     * <code>optional string bssid = 6;</code>
     */
    private void setBssidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bssid_ = value.toStringUtf8();
    }

    public static final int SSID_FIELD_NUMBER = 7;
    private String ssid_;
    /**
     * <code>optional string ssid = 7;</code>
     */
    public String getSsid() {
      return ssid_;
    }
    /**
     * <code>optional string ssid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSsidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ssid_);
    }
    /**
     * <code>optional string ssid = 7;</code>
     */
    private void setSsid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ssid_ = value;
    }
    /**
     * <code>optional string ssid = 7;</code>
     */
    private void clearSsid() {
      
      ssid_ = getDefaultInstance().getSsid();
    }
    /**
     * <code>optional string ssid = 7;</code>
     */
    private void setSsidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ssid_ = value.toStringUtf8();
    }

    public static final int SN_FIELD_NUMBER = 8;
    private String sn_;
    /**
     * <code>optional string sn = 8;</code>
     */
    public String getSn() {
      return sn_;
    }
    /**
     * <code>optional string sn = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sn_);
    }
    /**
     * <code>optional string sn = 8;</code>
     */
    private void setSn(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sn_ = value;
    }
    /**
     * <code>optional string sn = 8;</code>
     */
    private void clearSn() {
      
      sn_ = getDefaultInstance().getSn();
    }
    /**
     * <code>optional string sn = 8;</code>
     */
    private void setSnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sn_ = value.toStringUtf8();
    }

    public static final int LAC_FIELD_NUMBER = 9;
    private String lac_;
    /**
     * <code>optional string lac = 9;</code>
     */
    public String getLac() {
      return lac_;
    }
    /**
     * <code>optional string lac = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLacBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lac_);
    }
    /**
     * <code>optional string lac = 9;</code>
     */
    private void setLac(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lac_ = value;
    }
    /**
     * <code>optional string lac = 9;</code>
     */
    private void clearLac() {
      
      lac_ = getDefaultInstance().getLac();
    }
    /**
     * <code>optional string lac = 9;</code>
     */
    private void setLacBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lac_ = value.toStringUtf8();
    }

    public static final int CID_FIELD_NUMBER = 10;
    private String cid_;
    /**
     * <code>optional string cid = 10;</code>
     */
    public String getCid() {
      return cid_;
    }
    /**
     * <code>optional string cid = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cid_);
    }
    /**
     * <code>optional string cid = 10;</code>
     */
    private void setCid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cid_ = value;
    }
    /**
     * <code>optional string cid = 10;</code>
     */
    private void clearCid() {
      
      cid_ = getDefaultInstance().getCid();
    }
    /**
     * <code>optional string cid = 10;</code>
     */
    private void setCidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cid_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nbaps_.size(); i++) {
        output.writeMessage(1, nbaps_.get(i));
      }
      if (!pwd_.isEmpty()) {
        output.writeString(2, getPwd());
      }
      if (shareType_ != 0) {
        output.writeSInt32(3, shareType_);
      }
      if (securityLevel_ != 0) {
        output.writeSInt32(4, securityLevel_);
      }
      if (authType_ != 0) {
        output.writeSInt32(5, authType_);
      }
      if (!bssid_.isEmpty()) {
        output.writeString(6, getBssid());
      }
      if (!ssid_.isEmpty()) {
        output.writeString(7, getSsid());
      }
      if (!sn_.isEmpty()) {
        output.writeString(8, getSn());
      }
      if (!lac_.isEmpty()) {
        output.writeString(9, getLac());
      }
      if (!cid_.isEmpty()) {
        output.writeString(10, getCid());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nbaps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nbaps_.get(i));
      }
      if (!pwd_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPwd());
      }
      if (shareType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, shareType_);
      }
      if (securityLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, securityLevel_);
      }
      if (authType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, authType_);
      }
      if (!bssid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getBssid());
      }
      if (!ssid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getSsid());
      }
      if (!sn_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getSn());
      }
      if (!lac_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getLac());
      }
      if (!cid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getCid());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApShareRequestBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApShareRequestBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApShareRequestBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApShareRequestBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApShareRequestBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApShareRequestBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApShareRequestBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApShareRequestBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApShareRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApShareRequestBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApShareRequestBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApShareRequestBean, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean)
        ApShareRequestBeanOrBuilder {
      // Construct using com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBeanOuterClass.ApShareRequestBean.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public java.util.List<Nbaps> getNbapsList() {
        return java.util.Collections.unmodifiableList(
            instance.getNbapsList());
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public int getNbapsCount() {
        return instance.getNbapsCount();
      }/**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Nbaps getNbaps(int index) {
        return instance.getNbaps(index);
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder setNbaps(
          int index, Nbaps value) {
        copyOnWrite();
        instance.setNbaps(index, value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder setNbaps(
          int index, Nbaps.Builder builderForValue) {
        copyOnWrite();
        instance.setNbaps(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder addNbaps(Nbaps value) {
        copyOnWrite();
        instance.addNbaps(value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder addNbaps(
          int index, Nbaps value) {
        copyOnWrite();
        instance.addNbaps(index, value);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder addNbaps(
          Nbaps.Builder builderForValue) {
        copyOnWrite();
        instance.addNbaps(builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder addNbaps(
          int index, Nbaps.Builder builderForValue) {
        copyOnWrite();
        instance.addNbaps(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder addAllNbaps(
          Iterable<? extends Nbaps> values) {
        copyOnWrite();
        instance.addAllNbaps(values);
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder clearNbaps() {
        copyOnWrite();
        instance.clearNbaps();
        return this;
      }
      /**
       * <code>repeated .com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean.Nbaps nbaps = 1;</code>
       */
      public Builder removeNbaps(int index) {
        copyOnWrite();
        instance.removeNbaps(index);
        return this;
      }

      /**
       * <code>optional string pwd = 2;</code>
       */
      public String getPwd() {
        return instance.getPwd();
      }
      /**
       * <code>optional string pwd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPwdBytes() {
        return instance.getPwdBytes();
      }
      /**
       * <code>optional string pwd = 2;</code>
       */
      public Builder setPwd(
          String value) {
        copyOnWrite();
        instance.setPwd(value);
        return this;
      }
      /**
       * <code>optional string pwd = 2;</code>
       */
      public Builder clearPwd() {
        copyOnWrite();
        instance.clearPwd();
        return this;
      }
      /**
       * <code>optional string pwd = 2;</code>
       */
      public Builder setPwdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPwdBytes(value);
        return this;
      }

      /**
       * <code>optional sint32 shareType = 3;</code>
       */
      public int getShareType() {
        return instance.getShareType();
      }
      /**
       * <code>optional sint32 shareType = 3;</code>
       */
      public Builder setShareType(int value) {
        copyOnWrite();
        instance.setShareType(value);
        return this;
      }
      /**
       * <code>optional sint32 shareType = 3;</code>
       */
      public Builder clearShareType() {
        copyOnWrite();
        instance.clearShareType();
        return this;
      }

      /**
       * <code>optional sint32 securityLevel = 4;</code>
       */
      public int getSecurityLevel() {
        return instance.getSecurityLevel();
      }
      /**
       * <code>optional sint32 securityLevel = 4;</code>
       */
      public Builder setSecurityLevel(int value) {
        copyOnWrite();
        instance.setSecurityLevel(value);
        return this;
      }
      /**
       * <code>optional sint32 securityLevel = 4;</code>
       */
      public Builder clearSecurityLevel() {
        copyOnWrite();
        instance.clearSecurityLevel();
        return this;
      }

      /**
       * <code>optional sint32 authType = 5;</code>
       */
      public int getAuthType() {
        return instance.getAuthType();
      }
      /**
       * <code>optional sint32 authType = 5;</code>
       */
      public Builder setAuthType(int value) {
        copyOnWrite();
        instance.setAuthType(value);
        return this;
      }
      /**
       * <code>optional sint32 authType = 5;</code>
       */
      public Builder clearAuthType() {
        copyOnWrite();
        instance.clearAuthType();
        return this;
      }

      /**
       * <code>optional string bssid = 6;</code>
       */
      public String getBssid() {
        return instance.getBssid();
      }
      /**
       * <code>optional string bssid = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBssidBytes() {
        return instance.getBssidBytes();
      }
      /**
       * <code>optional string bssid = 6;</code>
       */
      public Builder setBssid(
          String value) {
        copyOnWrite();
        instance.setBssid(value);
        return this;
      }
      /**
       * <code>optional string bssid = 6;</code>
       */
      public Builder clearBssid() {
        copyOnWrite();
        instance.clearBssid();
        return this;
      }
      /**
       * <code>optional string bssid = 6;</code>
       */
      public Builder setBssidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBssidBytes(value);
        return this;
      }

      /**
       * <code>optional string ssid = 7;</code>
       */
      public String getSsid() {
        return instance.getSsid();
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        return instance.getSsidBytes();
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public Builder setSsid(
          String value) {
        copyOnWrite();
        instance.setSsid(value);
        return this;
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public Builder clearSsid() {
        copyOnWrite();
        instance.clearSsid();
        return this;
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public Builder setSsidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSsidBytes(value);
        return this;
      }

      /**
       * <code>optional string sn = 8;</code>
       */
      public String getSn() {
        return instance.getSn();
      }
      /**
       * <code>optional string sn = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        return instance.getSnBytes();
      }
      /**
       * <code>optional string sn = 8;</code>
       */
      public Builder setSn(
          String value) {
        copyOnWrite();
        instance.setSn(value);
        return this;
      }
      /**
       * <code>optional string sn = 8;</code>
       */
      public Builder clearSn() {
        copyOnWrite();
        instance.clearSn();
        return this;
      }
      /**
       * <code>optional string sn = 8;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSnBytes(value);
        return this;
      }

      /**
       * <code>optional string lac = 9;</code>
       */
      public String getLac() {
        return instance.getLac();
      }
      /**
       * <code>optional string lac = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLacBytes() {
        return instance.getLacBytes();
      }
      /**
       * <code>optional string lac = 9;</code>
       */
      public Builder setLac(
          String value) {
        copyOnWrite();
        instance.setLac(value);
        return this;
      }
      /**
       * <code>optional string lac = 9;</code>
       */
      public Builder clearLac() {
        copyOnWrite();
        instance.clearLac();
        return this;
      }
      /**
       * <code>optional string lac = 9;</code>
       */
      public Builder setLacBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLacBytes(value);
        return this;
      }

      /**
       * <code>optional string cid = 10;</code>
       */
      public String getCid() {
        return instance.getCid();
      }
      /**
       * <code>optional string cid = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCidBytes() {
        return instance.getCidBytes();
      }
      /**
       * <code>optional string cid = 10;</code>
       */
      public Builder setCid(
          String value) {
        copyOnWrite();
        instance.setCid(value);
        return this;
      }
      /**
       * <code>optional string cid = 10;</code>
       */
      public Builder clearCid() {
        copyOnWrite();
        instance.clearCid();
        return this;
      }
      /**
       * <code>optional string cid = 10;</code>
       */
      public Builder setCidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCidBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApShareRequestBean();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          nbaps_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApShareRequestBean other = (ApShareRequestBean) arg1;
          nbaps_= visitor.visitList(nbaps_, other.nbaps_);
          pwd_ = visitor.visitString(!pwd_.isEmpty(), pwd_,
              !other.pwd_.isEmpty(), other.pwd_);
          shareType_ = visitor.visitInt(shareType_ != 0, shareType_,
              other.shareType_ != 0, other.shareType_);
          securityLevel_ = visitor.visitInt(securityLevel_ != 0, securityLevel_,
              other.securityLevel_ != 0, other.securityLevel_);
          authType_ = visitor.visitInt(authType_ != 0, authType_,
              other.authType_ != 0, other.authType_);
          bssid_ = visitor.visitString(!bssid_.isEmpty(), bssid_,
              !other.bssid_.isEmpty(), other.bssid_);
          ssid_ = visitor.visitString(!ssid_.isEmpty(), ssid_,
              !other.ssid_.isEmpty(), other.ssid_);
          sn_ = visitor.visitString(!sn_.isEmpty(), sn_,
              !other.sn_.isEmpty(), other.sn_);
          lac_ = visitor.visitString(!lac_.isEmpty(), lac_,
              !other.lac_.isEmpty(), other.lac_);
          cid_ = visitor.visitString(!cid_.isEmpty(), cid_,
              !other.cid_.isEmpty(), other.cid_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!nbaps_.isModifiable()) {
                    nbaps_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(nbaps_);
                  }
                  nbaps_.add(
                      input.readMessage(Nbaps.parser(), extensionRegistry));
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  pwd_ = s;
                  break;
                }
                case 24: {

                  shareType_ = input.readSInt32();
                  break;
                }
                case 32: {

                  securityLevel_ = input.readSInt32();
                  break;
                }
                case 40: {

                  authType_ = input.readSInt32();
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  bssid_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  ssid_ = s;
                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();

                  sn_ = s;
                  break;
                }
                case 74: {
                  String s = input.readStringRequireUtf8();

                  lac_ = s;
                  break;
                }
                case 82: {
                  String s = input.readStringRequireUtf8();

                  cid_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApShareRequestBean.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.ap.web.cmd.shareap.v3.protobuf.ApShareRequestBean)
    private static final ApShareRequestBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApShareRequestBean();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApShareRequestBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApShareRequestBean> PARSER;

    public static com.google.protobuf.Parser<ApShareRequestBean> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
