/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_breakpad_NdkMonitorManager */

#ifndef _Included_com_example_breakpad_NdkMonitorManager
#define _Included_com_example_breakpad_NdkMonitorManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_breakpad_NdkMonitorManager
 * Method:    setUpBreakpad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_breakpad_NdkMonitorManager_setUpBreakpad
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_breakpad_NdkMonitorManager
 * Method:    nativeCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_breakpad_NdkMonitorManager_nativeCrash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
