// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufResponseModel.proto

package com.halo.domain.www.controller.protobuf;

public final class ProtobufResponseModelOuterClass {
  private ProtobufResponseModelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ProtobufResponseModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.halo.domain.www.controller.protobuf.ProtobufResponseModel)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string code = 1;</code>
     */
    String getCode();
    /**
     * <code>optional string code = 1;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional string msg = 2;</code>
     */
    String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */
    int getSnCount();
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */
    boolean containsSn(
            String key);
    /**
     * Use {@link #getSnMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getSn();
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */
    java.util.Map<String, String>
    getSnMap();
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */

    String getSnOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */

    String getSnOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code com.halo.domain.www.controller.protobuf.ProtobufResponseModel}
   */
  public  static final class ProtobufResponseModel extends
      com.google.protobuf.GeneratedMessageLite<
          ProtobufResponseModel, ProtobufResponseModel.Builder> implements
      // @@protoc_insertion_point(message_implements:com.halo.domain.www.controller.protobuf.ProtobufResponseModel)
      ProtobufResponseModelOrBuilder {
    private ProtobufResponseModel() {
      code_ = "";
      msg_ = "";
    }
    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private String code_;
    /**
     * <code>optional string code = 1;</code>
     */
    public String getCode() {
      return code_;
    }
    /**
     * <code>optional string code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(code_);
    }
    /**
     * <code>optional string code = 1;</code>
     */
    private void setCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
    }
    /**
     * <code>optional string code = 1;</code>
     */
    private void clearCode() {
      
      code_ = getDefaultInstance().getCode();
    }
    /**
     * <code>optional string code = 1;</code>
     */
    private void setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value.toStringUtf8();
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private String msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public String getMsg() {
      return msg_;
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(msg_);
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    private void setMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    private void clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    private void setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value.toStringUtf8();
    }

    public static final int SN_FIELD_NUMBER = 3;
    private static final class SnDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          String, String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<String, String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        String, String> sn_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<String, String>
    internalGetSn() {
      return sn_;
    }
    private com.google.protobuf.MapFieldLite<String, String>
    internalGetMutableSn() {
      if (!sn_.isMutable()) {
        sn_ = sn_.mutableCopy();
      }
      return sn_;
    }

    public int getSnCount() {
      return internalGetSn().size();
    }
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */

    public boolean containsSn(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetSn().containsKey(key);
    }
    /**
     * Use {@link #getSnMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getSn() {
      return getSnMap();
    }
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */

    public java.util.Map<String, String> getSnMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetSn());
    }
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */

    public String getSnOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetSn();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */

    public String getSnOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetSn();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; sn = 3;</code>
     */
    private java.util.Map<String, String>
    getMutableSnMap() {
      return internalGetMutableSn();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!code_.isEmpty()) {
        output.writeString(1, getCode());
      }
      if (!msg_.isEmpty()) {
        output.writeString(2, getMsg());
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetSn().entrySet()) {
        SnDefaultEntryHolder.defaultEntry.serializeTo(
            output, 3, entry.getKey(), entry.getValue());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!code_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCode());
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMsg());
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetSn().entrySet()) {
        size += SnDefaultEntryHolder.defaultEntry.computeMessageSize(
          3, entry.getKey(), entry.getValue());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ProtobufResponseModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProtobufResponseModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProtobufResponseModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProtobufResponseModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProtobufResponseModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProtobufResponseModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProtobufResponseModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProtobufResponseModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProtobufResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProtobufResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtobufResponseModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.halo.domain.www.controller.protobuf.ProtobufResponseModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProtobufResponseModel, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.halo.domain.www.controller.protobuf.ProtobufResponseModel)
        ProtobufResponseModelOrBuilder {
      // Construct using com.halo.domain.www.controller.protobuf.ProtobufResponseModelOuterClass.ProtobufResponseModel.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string code = 1;</code>
       */
      public String getCode() {
        return instance.getCode();
      }
      /**
       * <code>optional string code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        return instance.getCodeBytes();
      }
      /**
       * <code>optional string code = 1;</code>
       */
      public Builder setCode(
          String value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <code>optional string code = 1;</code>
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }
      /**
       * <code>optional string code = 1;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCodeBytes(value);
        return this;
      }

      /**
       * <code>optional string msg = 2;</code>
       */
      public String getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        return instance.getMsgBytes();
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          String value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgBytes(value);
        return this;
      }


      public int getSnCount() {
        return instance.getSnMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; sn = 3;</code>
       */

      public boolean containsSn(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return instance.getSnMap().containsKey(key);
      }

      public Builder clearSn() {
        copyOnWrite();
        instance.getMutableSnMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; sn = 3;</code>
       */

      public Builder removeSn(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        copyOnWrite();
        instance.getMutableSnMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getSnMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getSn() {
        return getSnMap();
      }
      /**
       * <code>map&lt;string, string&gt; sn = 3;</code>
       */
      public java.util.Map<String, String> getSnMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getSnMap());
      }
      /**
       * <code>map&lt;string, string&gt; sn = 3;</code>
       */

      public String getSnOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            instance.getSnMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; sn = 3;</code>
       */

      public String getSnOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            instance.getSnMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; sn = 3;</code>
       */
      public Builder putSn(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        copyOnWrite();
        instance.getMutableSnMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; sn = 3;</code>
       */
      public Builder putAllSn(
          java.util.Map<String, String> values) {
        copyOnWrite();
        instance.getMutableSnMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.halo.domain.www.controller.protobuf.ProtobufResponseModel)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProtobufResponseModel();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          sn_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ProtobufResponseModel other = (ProtobufResponseModel) arg1;
          code_ = visitor.visitString(!code_.isEmpty(), code_,
              !other.code_.isEmpty(), other.code_);
          msg_ = visitor.visitString(!msg_.isEmpty(), msg_,
              !other.msg_.isEmpty(), other.msg_);
          sn_ = visitor.visitMap(
              sn_, other.internalGetSn());
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  code_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  msg_ = s;
                  break;
                }
                case 26: {
                  if (!sn_.isMutable()) {
                    sn_ = sn_.mutableCopy();
                  }
                  SnDefaultEntryHolder.defaultEntry.parseInto(sn_, input, extensionRegistry);  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ProtobufResponseModel.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.halo.domain.www.controller.protobuf.ProtobufResponseModel)
    private static final ProtobufResponseModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtobufResponseModel();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ProtobufResponseModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ProtobufResponseModel> PARSER;

    public static com.google.protobuf.Parser<ProtobufResponseModel> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
